### ISSUE TITLE
Board missing UNKNOWN

### ISSUE THREAD

**Issue by patboul** [rbonghi/jetson_stats#103]
Please update jetson-stats with this board

**Board**
 - Board(s): UNKNOWN
 - Boardis: 
 - SOC: tegra194
 - ID: 25
 - Code Name: R32_4_3_Xavier-NX_AN110_Camera_IMX290_Dual_1.dts

**Jetpack**
 - Jetpack: 4.4
 - L4T: 32.4.3

**Jetson-Stats**
 - version: 3.0.1

**Comment by rbonghi** [comment]
Please update jetson-stats to **3.0.1**
```
sudo -H pip install -U jetson-stats
```
and reboot your board
(Check #90)
