### ISSUE TITLE
Is jtop display GPU usage while doing video decoding/encoding hardware acceleration?

### ISSUE THREAD

**Issue by HaifeiYang** [rbonghi/jetson_stats#111]
I know that GPU on Jetson use nvdec/nvenc to accelerate video encoding/decoding from 
[nvidia-video-codec-sdk](https://developer.nvidia.com/nvidia-video-codec-sdk)
But I want to know if jtop display GPU usage while doing video decoding/encoding hardware acceleration?
If not, how do I monitor the usage of nvdec/nvenc?
Thanks!

**Comment by bharatik-IISc** [comment]
I have the same question.

**Comment by rbonghi** [comment]
I don't have access for each process the engine use, but I can ready the shared memory used on Jetson.

![Screenshot from 2022-12-31 13-14-25](https://user-images.githubusercontent.com/4551246/210761317-0e81f39a-f398-4585-a80a-f2e2bc1a8f6e.png)

The final release will be out at the end of this day. Keep ready to try it.
Meanwhile close this issue, if there are new suggestion feel free to reopen it
