### ISSUE TITLE
Jetpack missing [L4T e.g. 5.2.1]

### ISSUE THREAD

**Issue by yoshidasadao** [rbonghi/jetson_stats#115]
Please update jetson-stats with new jetpack

**Linux for Tegra**
 - L4T: [e.g. 4.3]

**Jetson-Stats**

 - Version: [e.g. 1.8]

**Comment by rbonghi** [comment]
Please update jetson-stats to 3.0.2

sudo -H pip install -U jetson-stats
and reboot your board
(Check #90)
