### ISSUE TITLE
Change color for hot temperatures

### ISSUE THREAD

**Issue by Myzhar** [rbonghi/jetson_stats#118]
Red temperatures are not visible for color blinded

**Comment by rbonghi** [comment]
I will make a new option on jtop and also settable via an environment variable to change the base colors

`jtop -cb` or `JETSON_STATS_CB`

I will publish this update in the next jetson-stats release candidate

**Comment by rbonghi** [comment]
This new feature has been added in the next release!

You can run with this new option
```
jtop --color-filter
```

Or add in your bashrc

 ```
JTOP_COLOR_FILTER=True
````

**Comment by rbonghi** [comment]
New feature released!
