### ISSUE TITLE
Jetpack missing [L4T 32.5.0]

### ISSUE THREAD

**Issue by neuroquantifier** [rbonghi/jetson_stats#125]
Please update jetson-stats with new jetpack

**Linux for Tegra**
 - L4T: 32.5.0

**Jetson-Stats**
 - Version: 3.0.2

I did a fresh install and got this missing message.

**Comment by rbonghi** [comment]
Fixed

Please update your jetson-stats with:
```
sudo -H pip install -U jetson-stats
```
and reboot your board
