### ISSUE TITLE
Request M2 drive status and updated board info

### ISSUE THREAD

**Issue by Rotoslider** [rbonghi/jetson_stats#135]
I have a 32gb Jetson AGX with a 512gb M2 drive. Jtop shows it as a 16gb model and does not show the M2 drive.
Also the voltage supply mentioned earlier would be a great addition.
You have a nice program it should come included with the Jetson. Nice work
thank you
![Jtop AGX wrong version](https://user-images.githubusercontent.com/15005663/107550724-3d1c8100-6b86-11eb-9169-ca0c86e2d805.png)

**Comment by Rotoslider** [comment]
![Jtop AGX wrong info](https://user-images.githubusercontent.com/15005663/107550825-5cb3a980-6b86-11eb-941b-212d49fd8594.png)
Really nice program

**Comment by rbonghi** [comment]
Hi @Rotoslider,

About the M2 drive, I will take a look at how to implement it in jtop, the same story for #131 
About the 32GB AGX Xavier bug I will fix it soon. #87

**Comment by rbonghi** [comment]
This error should now be fixed with the latest release **4.0** try to install and check again
```
sudo -H pip install -U jetson-stats
```
