### ISSUE TITLE
jetson-stats not supported for [L4T 32.5.1]

### ISSUE THREAD

**Issue by diamondbarcode** [rbonghi/jetson_stats#138]
Please update jetson-stats with new jetpack

**Linux for Tegra**
 - L4T: 32.5.1

**Jetson-Stats**
 - Version: 3.0.3

i got this warning when i exit jtop but everything seem to work just fine.

**Comment by rbonghi** [comment]
WOW!
just released now! :-D
I will fix it before the end of this week ;-)

**Comment by rbonghi** [comment]
Please update jetson-stats to **3.1.0**
```
sudo -H pip install -U jetson-stats
```
and reboot your board
