### ISSUE TITLE
jetson-stats not supported for [L4T 32.5.1]

### ISSUE THREAD

**Issue by sauravkumar-volt** [rbonghi/jetson_stats#139]
Please update jetson-stats with new jetpack

**Linux for Tegra**
 - L4T: 32.5.1

**Jetson-Stats**
 - Version: 3.0.3

**Comment by rbonghi** [comment]
Please update jetson-stats to **3.1.0** (Check #138)
```
sudo -H pip install -U jetson-stats
```
and reboot your board
