### ISSUE TITLE
Xavier NX production version show as developer kit

### ISSUE THREAD

**Issue by kubikula1** [rbonghi/jetson_stats#143]
Hello, 
we have xavier nx  production version - definitely it is production version because it has internal emmc storage. 
The board type is incorrectly marked as Developer Kit Version.
Note that we dont' boot from the emmc storage but from sd card - emmc is too small for us. So the flash was made by cmd:
`sudo ./flash.sh jetson-xavier-nx-devkit-emmc mmcblk0p1`
Yes, there is discrepancy from nvidia - for flash production version you must used` jetson-xavier-nx-devkit-emmc`
Maybe this is the problem, why is the  board type wrong.

![screen_2021-03-08 12-12-01](https://user-images.githubusercontent.com/44328757/110314103-b5e8ee80-8007-11eb-8648-da993b4ee4da.png)

![screen_2021-03-08 12-12-51](https://user-images.githubusercontent.com/44328757/110314155-cb5e1880-8007-11eb-9eb9-3adaf28616ff.png)

Otherwise thanks for the great utility

**Comment by rbonghi** [comment]
This error should now be fixed with the latest release **4.0** try to install and check again
```
sudo -H pip install -U jetson-stats
```
