### ISSUE TITLE
The jetson_stats.service is not active

### ISSUE THREAD

**Issue by ioir123ju** [rbonghi/jetson_stats#156]
I can't run jtop.
**environment**
xavier NX.
jetpack 4.2.

**problem**
![image](https://user-images.githubusercontent.com/14951957/123186779-74ebeb80-d4cb-11eb-809a-e7f6925a06a4.png)
systemctl restart jetson_stats.service is not work.

**Comment by lmw0320** [comment]
have you sloved this problem？ I met the same error in docker container。。I want to use GPU in container but found the jetson-stats not install, and command jtop not found。 After installed the jetson-stats，this error occured. And I run the recommended command, It is useless.

**Comment by lmw0320** [comment]
have you sloved this problem？ I met the same error in docker container。。I want to use GPU in container but found the jetson-stats not install, and command jtop not found。 After installed the jetson-stats，this error occured. And I run the recommended command, It is useless.

**Comment by rbonghi** [comment]
If this error appears please open this issue again
