### ISSUE TITLE
Jetpack missing [L4T 32.5.1]

### ISSUE THREAD

**Issue by WisdomPill** [rbonghi/jetson_stats#157]
Please update jetson-stats with new jetpack

**Linux for Tegra**
 - L4T: 32.5.1

**Jetson-Stats**
 - Version: 3.0.2

**Comment by rbonghi** [comment]
Please update jetson-stats to **3.1.0** (Check #138)
```
sudo -H pip install -U jetson-stats
```
and reboot your board
