### ISSUE TITLE
Board missing P3509-0000

### ISSUE THREAD

**Issue by JoeyZhu** [rbonghi/jetson_stats#159]
Please update jetson-stats with this board

**Board**
 - Board(s): P3509-0000
 - Boardis: 3636:0001:A0
 - SOC: tegra186
 - ID: 24
 - Code Name: lanai

**Jetpack**
 - Jetpack: 4.5.1
 - L4T: 32.5.1

**Jetson-Stats**
 - version: 3.1.0

I am using tx2nx

**Comment by rbonghi** [comment]
Thx!

I will update jetson-stats soon.

I'm extremely busy at this period, but I'll do my best to update it :-)
