### ISSUE TITLE
Display calculated Amps

### ISSUE THREAD

**Issue by jarrah31** [rbonghi/jetson_stats#161]
**Describe the solution you'd like**
It would be nice if jtop could display amps alongside mW please.
I see that you kindly provided the formula to work it out from this issue (https://github.com/rbonghi/jetson_stats/issues/64), but it would be great if this could be done automatically and in real-time.
I would then use this information to determine if I’m using the correct power supply.

thanks.

**Comment by rbonghi** [comment]
Hi @jarrah31 ,

After an investigation, I cannot enable this feature. I don't know for each Jetson which is the power supply and the voltage is currently running for each field.

If something is change, I will be happy to integrate this new feature
