### ISSUE TITLE
AGX Xavier 16G or 32G? 

### ISSUE THREAD

**Issue by jiapei100** [rbonghi/jetson_stats#162]
**Is your feature request related to a problem? Please describe.**
My board is **P2822-0004**, rather than **P2822-0001**. However:
```console
➜  ~ jetson_release -v
 - NVIDIA Jetson AGX Xavier [16GB]
   * Jetpack 4.6 [L4T 32.6.1]
   * NV Power Mode: MODE_15W_DESKTOP - Type: 7
   * jetson_stats.service: active
 - Board info:
   * Type: AGX Xavier [16GB]
   * SOC Family: tegra194 - ID:25
   * Module: P2888-0001 - Board: P2822-0000
   * Code Name: galen
   * CUDA GPU architecture (ARCH_BIN): 7.2
   * Serial Number: 1421720004151
 - Libraries:
   * CUDA: 10.2.300
   * cuDNN: 8.2.1.32
   * TensorRT: 8.0.1.6
   * Visionworks: NOT_INSTALLED
   * OpenCV: 4.5.3-dev compiled CUDA: YES
   * VPI: ii libnvvpi1 1.1.11 arm64 NVIDIA Vision Programming Interface library
   * Vulkan: 1.2.70
 - jetson-stats:
   * Version 3.1.1
   * Works on Python 3.6.9
```
![Wrong Memory Size](https://raw.githubusercontent.com/LongerVision/Resource/master/AI/EdgeComputing/JetsonAGXXavier/AGX-Xavier-Memory-Size-16-or-32.png)

**Describe the solution you'd like**
Expecting the board is able to be detected correctly, as **P2888-0004** instead of **P2888-0001**, and of memory size 32G, instead of 16G.

**Describe alternatives you've considered**
It's clearly a **bug of jetson_stats** itself.

**Additional context**
N/A

**Comment by utpalpatel1507** [comment]
Is there any update on this? When the resolution will be provided?
