### ISSUE TITLE
Jetpack missing [L4T 32.6.1]

### ISSUE THREAD

**Issue by NSKernel** [rbonghi/jetson_stats#165]
Please update jetson-stats with new jetpack
**Linux for Tegra**
 - L4T: [32.6.1]
 - JetPack [4.6]

**Jetson-Stats**
 - Version: [3.1.0]

**Comment by rbonghi** [comment]
Fixed 86176da 

Please update jetson-stats to **3.1.1**
```
sudo -H pip install -U jetson-stats
```
and reboot your board
