### ISSUE TITLE
"This mode does not exist"

### ISSUE THREAD

**Issue by neilyoung** [rbonghi/jetson_stats#174]
I'm catching this message after having installed jetson-stats like so on a self-made Ubuntu 18.04 

`sudo -H python3 -m pip install -U jetson-stats 
`
I can see where this message is generated in the code, even though the "mode" is missing.

Do you have any pointer, how to simulate this message with "board means"?

**Comment by neilyoung** [comment]
Found it. Setting the mode works

https://github.com/rbonghi/jetson_stats/issues/148

**Comment by rbonghi** [comment]
Thx to remind me. I will work soon to update jetson-stats. I'm quite busy with another project. :-)

**Comment by neilyoung** [comment]
No problem. As long as setting the mode helps, all good
