### ISSUE TITLE
Board missing UNKNOWN

### ISSUE THREAD

**Issue by jasonbeach** [rbonghi/jetson_stats#181]
Please update jetson-stats with this board

**Board**
 - Board(s): UNKNOWN
 - Boardis: 
 - SOC: tegra194
 - ID: 25
 - Code Name: tegra194-xavier-nx-cti-NGX004.dts

**Jetpack**
 - Jetpack: 4.6
 - L4T: 32.6.1

**Jetson-Stats**
 - version: 3.1.1

**Comment by rbonghi** [comment]
Thank you! I think I will restart to rewrite the board detector.
