### ISSUE TITLE
Board missing UNKNOWN

### ISSUE THREAD

**Issue by superxh** [rbonghi/jetson_stats#182]
Please update jetson-stats with this board

**Board**
 - Board(s): UNKNOWN
 - Boardis: 3310:0000:A0
 - SOC: tegra186
 - ID: 24
 - Code Name: quill

**Jetpack**
 - Jetpack: 4.2.1
 - L4T: 32.2.0

**Jetson-Stats**
 - version: 3.1.1

**Comment by rbonghi** [comment]
Which board are you using?
