### ISSUE TITLE
jetson-stats not supported for [L4T 32.5.2]

### ISSUE THREAD

**Issue by enco77** [rbonghi/jetson_stats#185]
Please update jetson-stats with new jetpack

**Linux for Tegra**
 - L4T: 32.5.2

**Jetson-Stats**
 - Version: 3.1.1

**Comment by rbonghi** [comment]
Fixed

**Comment by rbonghi** [comment]
Please update jetson-stats to **3.1.2**

```
sudo -H pip install -U jetson-stats
```

and reboot your board
