### ISSUE TITLE
Board missing P3737-000

### ISSUE THREAD

**Issue by adujardin** [rbonghi/jetson_stats#208]
Please update jetson-stats with this board

**Board**
 - Board(s): P3737-000
 - Boardis: 
 - SOC: tegra23x
 - ID: 
 - Code Name: concord

**Jetpack**
 - Jetpack: UNKNOWN
 - L4T: 34.0.0

**Jetson-Stats**
 - version: 3.1.3

**Comment by rbonghi** [comment]
Update in progress, will be deployed in the new major release
