### ISSUE TITLE
OpenCV CUDA variables update

### ISSUE THREAD

**Issue by HoneyPatouceul** [rbonghi/jetson_stats#212]
Running L4T R32.6.1 on AGX Xavier. 
Seems recent opencv versions don't show "Use Cuda" in getBuildInformation() used by opencv_version --verbose.
Sorry I'm unable to make a PR, but it may be possible to get opencv CUDA availabilty with:
```
opencv_version --verbose | grep  "CUDA" | cut -f2 -d ':' | tr -s ' ' | cut -d' ' -f2
```
and opencv CUDA supported version with :
```
opencv_version --verbose | grep  "CUDA" | cut -f2 -d ':' | tr -s ' ' | cut -d' ' -f4 | cut -d',' -f1
```

**Comment by rbonghi** [comment]
Hi @HoneyPatouceul 

if I well understand I fixed using your hints:

https://github.com/rbonghi/jetson_stats/blob/develop/jtop/jetson_libraries#L35

and

https://github.com/rbonghi/jetson_stats/blob/develop/jtop/jetson_libraries#L49

Let me know if make sense for you as well

**Comment by HoneyPatouceul** [comment]
@rbonghi yes, that's the suggested change. Not tested, though. Feel free to close the issue when verified.

**Comment by rbonghi** [comment]
Thanks I will check for the new release
