### ISSUE TITLE
Access jtop data without gui

### ISSUE THREAD

**Issue by MaKaNu** [rbonghi/jetson_stats#213]
**Is your feature request related to a problem? Please describe.**
My Students connect remotely via MATLAB and I need a way to display them usage on the MATLAB prompt.

**Describe the solution you'd like**
This might be already possible but I couldn't figured out how. Example: Instead of opening the jtop gui I would like to call a specific python module (maybe jtop?) and read the gpu, cpu, or mem load at the moment.

**Describe alternatives you've considered**
For Mem and CPU I would normally stick to other utilities which provide this, but for gpu this I could not find another solution. I usually use gpustat but since nvidia-smi is not available, I hoped for jtop.

**Comment by rbonghi** [comment]
Hi @MaKaNu ,

There are different examples here to use jtop such as a python library:
https://github.com/rbonghi/jetson_stats/tree/master/examples
