### ISSUE TITLE
Missing OpenCV build from source

### ISSUE THREAD

**Issue by SEHAIRIKamal** [rbonghi/jetson_stats#214]
**bug description**
Hello all,
I have built OpenCV from source with Cuda support successfully. The python detects OpenCV correctly and returns its version, however, `Jetson_release -v `returns that OpenCV is not installed. Is there way to add the built OpenCV from source to system that can be detected using the command Jetson_release -v

**To Reproduce**
1. Delete the jetson nano pre-installed OpenCV
2. Download and build OpenCV rom source
3. run Jetson_release -v

**Screenshots**
![Screenshot from 2022-04-19 13-10-41](https://user-images.githubusercontent.com/23197960/164998733-42158bf1-90b3-4041-9091-db41712b7d3b.png)

**Board Jetson Nano**
 - SOC: [tegraX]
 - ID: [e.g. 10]
 - Board(s): Jetson Nano 4GB
 - Code Name:B01

**Jetpack**
 - Jetpack: 4.3

**Jetson-Stats**
 - Version: [e.g. 1.8]

**Comment by rbonghi** [comment]
should be fixed by #212
