### ISSUE TITLE
Board missing P3737-000

### ISSUE THREAD

**Issue by Eric-Marchetti** [rbonghi/jetson_stats#220]
Please update jetson-stats with this board

**Board**
 - Board(s): P3737-000
 - Boardis: 
 - SOC: tegra23x
 - ID: 
 - Code Name: concord

**Jetpack**
 - Jetpack: UNKNOWN
 - L4T: 34.1.0

**Jetson-Stats**
 - version: 3.1.3

**Comment by leonpano2006** [comment]
https://github.com/rbonghi/jetson_stats/issues/210
jetpack 5.0 with issue with missing_board

**Comment by rbonghi** [comment]
Add in my loop. Will be fixed in the new major release
