### ISSUE TITLE
jetson-stats not supported for [L4T 34.1.1]

### ISSUE THREAD

**Issue by lxq-iang** [rbonghi/jetson_stats#223]
Please update jetson-stats with new jetpack

**Linux for Tegra**
 - L4T: 34.1.1

**Jetson-Stats**
 - Version: 3.1.3

**Comment by liaoweiguo** [comment]
any progress

**Comment by rbonghi** [comment]
Yes, it is in progress. There are many new fixes to be able to use jtop on JP 5.0. I think I will release the first pre-release next week.

![image](https://user-images.githubusercontent.com/4551246/171114960-54729da4-4117-4ac2-a46a-f8c8ac340a59.png)

**Comment by rbonghi** [comment]
Now Jetpack added with the latest released **4.0**
```
sudo -H pip install -U jetson-stats
```
