### ISSUE TITLE
Do not have fan controller

### ISSUE THREAD

**Issue by cpymaple** [rbonghi/jetson_stats#234]
Hi, my device is Jetson NX and my environment is ubuntu 20.04. After I install the jetson_stats, it seems that I do not have the fan controller (jtop -> 5 ->but there is no button to control fan). And then I want to control the fan manually, but I do not have the pwm-fan folder in /sys/devices/pwm-fan. Do you know how to solve it ?

**Comment by cpymaple** [comment]
![2022-06-09 14-40-33 的屏幕截图](https://user-images.githubusercontent.com/80804464/172781607-1c23e625-d21e-49ce-b042-af67bab88436.png)
![2022-06-09 14-40-41 的屏幕截图](https://user-images.githubusercontent.com/80804464/172781613-40bed7a2-9ed7-48fd-95b1-51ab173d4f23.png)
![2022-06-09 14-41-18 的屏幕截图](https://user-images.githubusercontent.com/80804464/172781618-a88f74d5-4c0e-497d-bbbb-0667bd3c6ae6.png)

**Comment by rbonghi** [comment]
You are working with JP5.0 that is currently not supported. #224 
I will release soon a new version to manage it

**Comment by rbonghi** [comment]
If you want to test the new version [4.0.0rc1](https://github.com/rbonghi/jetson_stats/releases/tag/4.0.0rc1):

```
sudo -H pip install jetson-stats==4.0.0rc1
```

Please remember right now jtop is **unstable**, I'm still fixing other bugs

**Comment by rbonghi** [comment]
Hi @theofficialgman 
which Jetson are you using?

**Comment by rbonghi** [comment]
BTW: I found the same bug on old JP. I'm still fixing :-)

Thank you

**Comment by rbonghi** [comment]
This release should fix all these bugs
```
sudo -H pip install jetson-stats==4.0.0rc2
```
Please remember right now jtop is **unstable**, I'm still fixing other bugs

**Comment by cpymaple** [comment]
> If you want to test the new version [4.0.0rc1](https://github.com/rbonghi/jetson_stats/releases/tag/4.0.0rc1):
> 
> ```
> sudo -H pip install jetson-stats==4.0.0rc1
> ```
> 
> Please remember right now jtop is **unstable**, I'm still fixing other bugs

OK, thank you. I find a way to solve it.  1. sudo /usr/bin/jetson_clocks --fan, this command can turn on the fan. 2. /sys/devices/platform/pwm-fan/hwmon/hwmon4. In this folder, we can find pwm1 document, change the number( from 0-255 ) can change the speed of fan.
