### ISSUE TITLE
Board missing

### ISSUE THREAD

**Issue by mostafamoradipour** [rbonghi/jetson_stats#256]
Please update jetson-stats with this board

**Board**
 - Board(s): 
 - Boardis: 
 - SOC: tegra23x
 - ID: 
 - Code Name: concord

**Jetpack**
 - Jetpack: UNKNOWN
 - L4T: 34.1.1

**Jetson-Stats**
 - version: 3.1.4

**Comment by rbonghi** [comment]
This error should now be fixed with the latest release **4.0** try to install and check again
```
sudo -H pip install -U jetson-stats
```
