### ISSUE TITLE
cannot import name jtop

### ISSUE THREAD

**Issue by questrov** [rbonghi/jetson_stats#262]
get the error `cannot import  name jtop` with python 2.7.27 or with python3  3.6.9.   

Trying to run [this script](https://github.com/svcavallar/jetson-stats-grafana-dashboard/blob/master/jetson_stats_prometheus_collector.py) in Python3 for Prometheus [Grafana Dashboard](https://grafana.com/grafana/dashboards/14493-nvidia-jetson/)

Lost when it comes to python permissions and versions thing.  Any clues much appreciated.

**Comment by rbonghi** [comment]
Have you installed jtop?

looks from your post that it is not installed

```
sudo -H pip3 install -U jetson-stats
```
