### ISSUE TITLE
jetson-stats not supported for [L4T 35.1.0]

### ISSUE THREAD

**Issue by Hyeon-Hoo** [rbonghi/jetson_stats#263]
Please update jetson-stats with new jetpack

**Linux for Tegra**
 - L4T: 35.1.0

**Jetson-Stats**
 - Version: 3.1.4

When i run jtop, the following message is displayed.

[WARN] Board missing P2822-0000 (press CTRL + Click)
[WARN] jetson-stats not supported for [L4T 35.1.0]
  Please, try: sudo -H pip install -U jetson-stats
  or open an issue on Github (press CTRL + Click)

**Comment by rbonghi** [comment]
This error should now be fixed with the latest release **4.0** try to install and check again
```
sudo -H pip install -U jetson-stats
```
