### ISSUE TITLE
Board missing UNKNOWN

### ISSUE THREAD

**Issue by fastovetsilya** [rbonghi/jetson_stats#277]
Please update jetson-stats with this board

**Board**
 - Board(s): UNKNOWN
 - Boardis: 
 - SOC: tegra194
 - ID: 25
 - Code Name: tegra194-agx-cti-AGX103-IMX296-FPD.dts

**Jetpack**
 - Jetpack: 4.5
 - L4T: 32.5.0

**Jetson-Stats**
 - version: 3.1.4

**Comment by rbonghi** [comment]
This error should now be fixed with the latest release **4.0** try to install and check again
```
sudo -H pip install -U jetson-stats
```
