### ISSUE TITLE
Jetson Orin Developer Kit 中的错误 GUI

### ISSUE THREAD

**Issue by linzyjx** [rbonghi/jetson_stats#284]
**Describe the bug**
GUI wrong in Jetson Orin Developer Kit

1. Display order of CPU 10, 11, 12 is wrong.
2. Sensor CV0,1,2 display wrong.
3. Power display wrong in "VDDQ VDD2 1V8"?

**To Reproduce**

Not applicable.

**Screenshots**
![image](https://user-images.githubusercontent.com/8017477/197404693-e8f20b99-b2eb-4d8d-ba63-a6bc36f363b5.png)

**Expected behavior**
Not applicable.

**Additional context**
Not applicable.

**Board**
 - SOC:tegra23x
 - ID: [e.g. 10]
 - Board(s): Module: P3701-0000 - Carrier: P3737-0000
 - Code Name: concord

**Jetpack**
 - Jetpack:Jetpack 5.0.1 DP
 - L4T: 34.1.1

**Jetson-Stats**
 - Version: jtop 4.0.0rc2

**Comment by rbonghi** [comment]
![image](https://user-images.githubusercontent.com/4551246/199236220-6571ec84-9622-4ef4-8465-a8996ab46dac.png)
Still working to fix it. New RC I hope will be fix today :-)

**Comment by rbonghi** [comment]
Fully support Orin with the latest released **4.0**
```
sudo -H pip install -U jetson-stats
```
