### ISSUE TITLE
Retrieve Temperature Data via Python Script

### ISSUE THREAD

**Issue by timovr-dev** [rbonghi/jetson_stats#289]
I'm trying to get the temperature data within a python script.

I tried out the following:
```python
import jtop
stats_obj = jtop.jtop()
stats_obj.temperature() # Throws Key Error
```
Is it even possible to get board information like this?

**Comment by rbonghi** [comment]
Hi @timovr-dev ,

Welcome here!
You are wrongly access to jtop from a python script. Check the solution below:

```python
from jtop import jtop

with jtop() as jetson:
    # jetson.ok() will provide the proper update frequency
    while jetson.ok():
        # Read tegra temperature
        print(jetson.temperature)
```

Other examples you can find here: https://github.com/rbonghi/jetson_stats/tree/master/examples
