### ISSUE TITLE
ZSWAP support.

### ISSUE THREAD

**Issue by FPSychotic** [rbonghi/jetson_stats#29]
Could be possible add stats for  ZSWAP if is activated in kernel? It is a nice peace of software,congrats

**Comment by rbonghi** [comment]
Hi @FPSychotic ,

Thank you for your message, and for your issue!
I think it is possible, but I don't know how I can reproduce your scenario.

I'm looking from these pages:
- https://devtalk.nvidia.com/default/topic/1049281/jetson-nano/usb-3-boot-on-jetson-nano/post/5332039/#5332039
- https://syonyk.blogspot.com/2019/04/nvidia-jetson-nano-desktop-use-kernel-builds.html
- https://github.com/Syonyk/raspberry_pi_scripts/blob/master/zswap.sh

This is what are you looking?

**Comment by FPSychotic** [comment]
XD, well that is not a issue. I just added that feature to my kernel and used you soft by first time and I thought that maybe interest you.  I saw some commands and a script to get the info, but didn't get them work, as almost everything in Linux XD. Maybe you could be interested in link them here for you?

**Comment by FPSychotic** [comment]
Apart, that thing zswap works, is amazing, I could compile Librealsense2 without swap

**Comment by rbonghi** [comment]
Hi @FPSychotic ,

sorry if I write late, but I am in holiday :-)
It's a nice idea! I will study a way to implement it, I think is not hard to check, I should be follow this script https://github.com/Syonyk/raspberry_pi_scripts/blob/master/zswap.sh to read this information. 👍

**Comment by rbonghi** [comment]
Add extra information to show the zram

![image](https://user-images.githubusercontent.com/4551246/74090927-75880b80-4aa9-11ea-9905-5dba0f2f3ce4.png)

I can show for each zram the used status

**Comment by FPSychotic** [comment]
So fast...Thank you!

**Comment by rbonghi** [comment]
I added the new feature! :-)
Now you can read the status of each swap directly from the new page

![image](https://user-images.githubusercontent.com/4551246/74093500-c9571c80-4aca-11ea-9507-2a66d3587cb0.png)
