### ISSUE TITLE
Jetson_clocks.sh delay required even with R28.2

### ISSUE THREAD

**Issue by Myzhar** [rbonghi/jetson_stats#3]
Despite what is stated in this post:
https://devtalk.nvidia.com/default/topic/1027388/jetson-tx2/jetson_clock-sh-1-minute-delay/
the 60 seconds of delay after boot are still required in R28.2 to get all the CPUs and the GPU clocked at max frequency.

I tested removing the version control at line 
https://github.com/rbonghi/jetson_easy/blob/master/jetson/jetson_performance.sh#L102
and I reinstalled the service. During the next reboot the fan started to spin after 60 seconds and the clocks of all the CPUs and of the GPU has been correctly set to max frequency.

**Comment by Kiobod** [comment]
Experiencing the same issue. Regardless of wait time, jetson_clocks will not properly set CPU or GPU from boot, despite behaving as normal when interacted with manually.

**Comment by rbonghi** [comment]
A new release of jetson-stats will control the boot startup and will be more stable than before.

I didn’t test with last release of Jetpack, but maybe we will close this issue.

I’m thinking to add in jtop a countdown
