### ISSUE TITLE
Board missing UNKNOWN

### ISSUE THREAD

**Issue by JungHeum-Park** [rbonghi/jetson_stats#301]
Please update jetson-stats with this board

**Board**
 - Board(s): UNKNOWN
 - Boardis: 
 - SOC: tegra194
 - ID: 25
 - Code Name: jakku

**Jetpack**
 - Jetpack: 4.6
 - L4T: 32.6.1

**Jetson-Stats**
 - version: 3.1.4

I'm using avermedia NX215 with jetson xavier nx

**Comment by rbonghi** [comment]
This error should now be fixed with the latest release **4.0** try to install and check again
```
sudo -H pip install -U jetson-stats
```
