### ISSUE TITLE
Board missing UNKNOWN

### ISSUE THREAD

**Issue by leonpano2006** [rbonghi/jetson_stats#319]
Please update jetson-stats with this board

**Board**
 - Board(s): UNKNOWN
 - Boardis: 2595:0000:A0
 - SOC: tegra210b01
 - ID: 33
 - Code Name: nx

**Jetpack**
 - Jetpack: 4.3
 - L4T: 32.3.1

**Jetson-Stats**
 - version: 3.1.4

**Comment by rbonghi** [comment]
This error should now be fixed with the latest release **4.0** try to install and check again
```
sudo -H pip install -U jetson-stats
```
