### ISSUE TITLE
Memory utilization snapshot in the CPU and GPU memory

### ISSUE THREAD

**Issue by jasperchih** [rbonghi/jetson_stats#32]
Hi,

i am looking forward to see the dynamic CPU and GPU memory utilization report during training. could have idea on how to get it from jetson_stats ?

thanks million

jasper chih

**Comment by rbonghi** [comment]
Hi @jasperchih ,

I'm adding a new example to use jtop like a library: https://github.com/rbonghi/jetson_stats/blob/develop/examples/log_data.py

This is what are you looking?

Raffaello
