### ISSUE TITLE
4 Mem page will crash when terminal is not bigger then *x33

### ISSUE THREAD

**Issue by leonpano2006** [rbonghi/jetson_stats#335]
**Describe the bug**
4 Mem page will crash when terminal is not bigger then *x33

**To Reproduce**
1. Open jtop
2. Terminal is smaller then *x33 or is bigger 
3. Go to 4 Mem page
4. See error or when is bigger then make terminal smaller then will see error

**Screenshots**
![image](https://user-images.githubusercontent.com/58368166/212665002-3f09ef85-95d3-4b8f-b750-819f5edc815b.png)

**Expected behavior**
Not crash of course 
**Board**
Tested on jetson Xavier nx and Nintendo switch (2019)

**Jetson-Stats**
 - Version: 4.0.0

**Comment by rbonghi** [comment]
Thank you! I will fix for the next release
