### ISSUE TITLE
Missing / incorrect power values on AGX Orin (dev kit)

### ISSUE THREAD

**Issue by vebjornbl** [rbonghi/jetson_stats#344]
**Describe the bug**
The "ALL" value seems to be the VIN_SYS_5V0 value, which is the I/O ports according to [this](https://forums.developer.nvidia.com/t/tegrastats-monitoring/217088/5?u=user62045). It should be a separate entry and "ALL" needs to be updated. 

**Screenshots**
Screenshot showing values in Jetson Power GUI and jtop. 
![image](https://user-images.githubusercontent.com/61044107/214376399-0f11dc00-7726-4690-88c5-d87d9ecccfcd.png)

**Board**
 - SOC: tegra23x
 - ID: Not sure where to find this
 - Board(s): Module: P3701-0000 - Carrier: P3737-0000
 - Code Name: concord

**Jetpack**
 - Jetpack: 5.0.2 GA
 - L4T: 35.1.0

**Jetson-Stats**
 - Version: 4.0.0

**Comment by rbonghi** [comment]
Hi @vebjornbl ,

Thank you for this message and for pointing me to this issue.
I check the reason why doesn't appear on jtop and I keep you posted

**Comment by rbonghi** [comment]
Find out why it was missing (ref #51)
It will be fixed in my next coming release! Thank you for noticing this bug!

![image](https://user-images.githubusercontent.com/4551246/214390605-82b20050-b16b-4e4a-bcb9-3f11970796eb.png)
