### ISSUE TITLE
jtop GUI missing NVIDIA Jetson Orin NX

### ISSUE THREAD

**Issue by lakshanthad** [rbonghi/jetson_stats#369]
When I close the jtop window, this warning can be seen:
![1676013967980](https://user-images.githubusercontent.com/20147381/218028827-9531cdc2-6fcd-463d-8997-f4ada3f57f4c.png)

Here is the jtop output:

![1676013992388](https://user-images.githubusercontent.com/20147381/218028903-5b09be0c-c291-4b0c-af52-988e5d580e51.jpg)

I have already tried installing using **sudo pip3 install -U jetson-stats**, but no luck.

**Comment by rbonghi** [comment]
Thank you,
I see from your previous issue #362, this fix.
I will fix as well in the next coming version (Should be done by the end of this week)

**Comment by lakshanthad** [comment]
Thank you very much!

**Comment by rbonghi** [comment]
Fixed from jtop **4.1.5**

```
sudo pip3 install -U jetson-stats
```

**Comment by lakshanthad** [comment]
Great! Thank you very much!
