### ISSUE TITLE
GUI compact engine page missing for [NVIDIA Jetson TX2]

### ISSUE THREAD

**Issue by ibrahemshamta** [rbonghi/jetson_stats#387]
Please add a new jtop engine compact page for

### Board

 - Model: quill
 - 699-level Part Number: 699-83310-1000-B02 E.0
 - P-Number: p3310-1000
 - BoardIDs: p3310-0000-A0
 - Module: NVIDIA Jetson TX2
 - SoC: tegra186
 - CUDA Arch BIN: 6.2
 - Codename: Quill
 - L4T: 32.4.4
 - Jetpack: 4.4.1

### jetson-stats

 - Version: 4.1.5

### Screenshot engine page

Screenshot page from jtop engine page attached

**Comment by rbonghi** [comment]
Hi @ibrahemshamta ,

Thank you for your issue. Can you attach here a screenshot from the engine page, please?
