### ISSUE TITLE
running error: "KeyError: 'memory'"

### ISSUE THREAD

**Issue by shoc2005** [rbonghi/jetson_stats#390]
## Describe the bug

After installing without errors and running in the terminal: "jtop" or "sudo jtop". An error occurs:
Traceback (most recent call last):
  File "/usr/local/bin/jtop", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/jtop/__main__.py", line 146, in main
    with jtop(interval=interval) as jetson:
  File "/usr/local/lib/python3.8/dist-packages/jtop/jtop.py", line 1274, in __enter__
    self.start()
  File "/usr/local/lib/python3.8/dist-packages/jtop/jtop.py", line 1154, in start
    self._memory._initialize(self._controller, init['memory'])
KeyError: 'memory'

### Board
Software part of jetson-stats 4.2.0 - (c) 2023, Raffaello Bonghi
Model: Jetson-AGX - Jetpack 5.0.1 DP [L4T 34.1.1]
NV Power Mode[0]: MAXN
Serial Number: [XXX Show with: jetson_release -s XXX]
Hardware:
 - 699-level Part Number: 699-82888-0004-400 L.0
 - P-Number: p2888-0004
 - Module: NVIDIA Jetson AGX Xavier (32 GB ram)
 - SoC: tegra194
 - CUDA Arch BIN: 7.2
 - Codename: Galen
Platform:
 - Machine: aarch64
 - System: Linux
 - Distribution: Ubuntu 20.04 focal
 - Release: 5.10.65-tegra
 - Python: 3.8.10
jtop:
 - Version: 4.2.0
 - Service: Active
Libraries:
 - CUDA: 12.0.140
 - cuDNN: 8.3.2.49
 - TensorRT: 5.0.1
 - VPI: 2.0.14
 - Vulkan: 1.3.203
 - OpenCV: 4.5.4 - with CUDA: NO

* jetson-stats version: [e.g. 1.8]
* P-Number: [e.g. pXXXX-XXXX]
* Module: [e.g. NVIDIA Jetson XXX]
* Jetpack: [e.g. 4.3]
* L4T: [e.g. 5.2.1]

### Log from jtop.service

-- Logs begin at Thu 2022-04-21 15:54:39 EEST, end at Mon 2023-03-20 18:09:13 EET. --
Mar 14 11:06:45 jetsons-desktop systemd[1]: Started jtop service.
Mar 14 11:06:46 jetsons-desktop jtop[1208]: [INFO] jtop.service - Running on Python: 3.8.10
Mar 14 11:06:46 jetsons-desktop jtop[1208]: [INFO] jtop.core.common - fan loaded on /sys/devices/platform
Mar 14 11:06:47 jetsons-desktop jtop[1208]: [INFO] jtop.core.common - jetson_clocks loaded on /usr/bin/jetson_clocks
Mar 14 11:06:47 jetsons-desktop jtop[1208]: [INFO] jtop.core.engine - Special Engine group found: [dlaX]
Mar 14 11:06:47 jetsons-desktop jtop[1208]: [INFO] jtop.core.engine - Special Engine group found: [pvaX]
Mar 14 11:06:47 jetsons-desktop jtop[1208]: [INFO] jtop.core.engine - Engines found: [APE CVNAS DLA0 DLA1 NVDEC NVENC NVJPG PVA0 PVA1 SE VIC]
Mar 14 11:06:47 jetsons-desktop jtop[1208]: [INFO] jtop.core.common - tegrastats loaded on /usr/bin/tegrastats
Mar 14 11:06:47 jetsons-desktop jtop[1208]: [INFO] jtop.__main__ - jetson_stats 4.1.5 - server loaded
Mar 14 11:06:52 jetsons-desktop jtop[1539]: [ERROR] jtop.core.command - Terminating process: ['/usr/bin/jetson_clocks', '--show']
Mar 14 11:06:52 jetsons-desktop jtop[1539]: [WARNING] jtop.core.command - Process terminated: ['/usr/bin/jetson_clocks', '--show']
Mar 14 11:06:52 jetsons-desktop jtop[1539]: [ERROR] jtop.core.jetson_clocks - [0] [errno:-1] Process does not replied in time
Mar 14 11:06:54 jetsons-desktop jtop[1539]: [INFO] jtop.core.fan - Mode set system status=False
Mar 20 17:58:01 jetsons-desktop systemd[1]: Stopping jtop service...
Mar 20 17:58:01 jetsons-desktop jtop[1539]: [INFO] jtop.__main__ - Close service by signal 15
Mar 20 17:58:01 jetsons-desktop jtop[1527]: [INFO] jtop.__main__ - Close service by signal 15
Mar 20 17:58:01 jetsons-desktop jtop[1539]: [INFO] jtop.service - Force tegrastats close
Mar 20 17:58:01 jetsons-desktop jtop[1208]: [INFO] jtop.__main__ - Close service by signal 15
Mar 20 17:58:01 jetsons-desktop jtop[1208]: [INFO] jtop.service - Terminate subprocess
Mar 20 17:58:01 jetsons-desktop jtop[1208]: [INFO] jtop.service - Wait shutdown subprocess
Mar 20 17:58:01 jetsons-desktop jtop[1539]: Process JtopServer-1:
Mar 20 17:58:01 jetsons-desktop jtop[1539]: [INFO] jtop.__main__ - Close service by signal 15
Mar 20 17:58:02 jetsons-desktop jtop[1208]: [INFO] jtop.service - Service closed
Mar 20 17:58:02 jetsons-desktop systemd[1]: jtop.service: Succeeded.
Mar 20 17:58:02 jetsons-desktop systemd[1]: Stopped jtop service.
Mar 20 17:58:07 jetsons-desktop systemd[1]: Started jtop service.
Mar 20 17:58:08 jetsons-desktop jtop[270333]: [INFO] jtop.service - Running on Python: 3.8.10
Mar 20 17:58:08 jetsons-desktop jtop[270333]: [INFO] jtop.core.common - fan loaded on /sys/devices/platform
Mar 20 17:58:08 jetsons-desktop jtop[270333]: [INFO] jtop.core.common - jetson_clocks loaded on /usr/bin/jetson_clocks
Mar 20 17:58:08 jetsons-desktop jtop[270333]: [INFO] jtop.core.engine - Special Engine group found: [dlaX]
Mar 20 17:58:08 jetsons-desktop jtop[270333]: [INFO] jtop.core.engine - Special Engine group found: [pvaX]
Mar 20 17:58:08 jetsons-desktop jtop[270333]: [INFO] jtop.core.engine - Engines found: [APE CVNAS DLA0 DLA1 NVDEC NVENC NVJPG PVA0 PVA1 SE VIC]
Mar 20 17:58:08 jetsons-desktop jtop[270333]: [INFO] jtop.core.common - tegrastats loaded on /usr/bin/tegrastats
Mar 20 17:58:08 jetsons-desktop jtop[270333]: [INFO] jtop.__main__ - jetson_stats 4.1.5 - server loaded
Mar 20 17:58:10 jetsons-desktop jtop[270360]: [INFO] jtop.core.fan - Mode set system status=False
Mar 20 17:59:38 jetsons-desktop jtop[270360]: [INFO] jtop.service - tegrastats started 1000ms
Mar 20 17:59:41 jetsons-desktop jtop[270360]: [INFO] jtop.service - tegrastats close
Mar 20 17:59:41 jetsons-desktop jtop[270360]: [INFO] jtop.service - jetson_clocks show closed
Mar 20 17:59:59 jetsons-desktop jtop[270360]: [INFO] jtop.service - tegrastats started 1000ms
Mar 20 18:00:02 jetsons-desktop jtop[270360]: [INFO] jtop.service - tegrastats close
Mar 20 18:00:02 jetsons-desktop jtop[270360]: [INFO] jtop.service - jetson_clocks show closed
Mar 20 18:00:04 jetsons-desktop jtop[270360]: [INFO] jtop.service - tegrastats started 1000ms
Mar 20 18:00:07 jetsons-desktop jtop[270360]: [INFO] jtop.service - tegrastats close
Mar 20 18:00:07 jetsons-desktop jtop[270360]: [INFO] jtop.service - jetson_clocks show closed
Mar 20 18:00:55 jetsons-desktop jtop[270360]: [INFO] jtop.service - tegrastats started 1000ms
Mar 20 18:00:58 jetsons-desktop jtop[270360]: [INFO] jtop.service - tegrastats close
Mar 20 18:00:58 jetsons-desktop jtop[270360]: [INFO] jtop.service - jetson_clocks show closed
Mar 20 18:05:21 jetsons-desktop jtop[270360]: [INFO] jtop.service - tegrastats started 1000ms
Mar 20 18:05:24 jetsons-desktop jtop[270360]: [INFO] jtop.service - tegrastats close
Mar 20 18:05:24 jetsons-desktop jtop[270360]: [INFO] jtop.service - jetson_clocks show closed

### Log from jetson-stats installation

Requirement already up-to-date: jetson-stats in /usr/local/lib/python3.8/dist-packages (4.2.0)
Requirement already satisfied, skipping upgrade: smbus2 in /usr/local/lib/python3.8/dist-packages (from jetson-stats) (0.4.2)
Requirement already satisfied, skipping upgrade: distro in /usr/lib/python3/dist-packages (from jetson-stats) (1.4.0)

**Comment by skyCreateXian** [comment]
Yes, I also encountered this error
Hardware Orin AGX
Software jetpack 5.0.2
This issue has been occurring since reinstalling Jetpack, Jetson stats version 4.2.0

**Comment by skyCreateXian** [comment]
I also have this problem, Perhaps it is because jtop does not support using from the serial port. After logging in through ssh, jtop can be used normally.

**Comment by tanghaom** [comment]
run:
sudo systemctl restart jtop
It will be ok.

**Comment by YunghuiHsu** [comment]
> run: sudo systemctl restart jtop It will be ok.

@tanghaom  Thanks  it works for me

**Comment by rbonghi** [comment]
I'm closing this issue if works.
Please reopen if this error reappears.
