### ISSUE TITLE
Random poping error

### ISSUE THREAD

**Issue by leonpano2006** [rbonghi/jetson_stats#395]
## To Reproduce

1. jtop
2. Did nothing
3. See error

## Screenshots

https://cdn.discordapp.com/attachments/1060564539529252954/1095627161534218322/098E858A-0EC4-43EC-B956-0491665F9ED6.jpg

**Comment by rbonghi** [comment]
Thank you I will take a look soon

**Comment by leonpano2006** [comment]
And jtop is a bit resource consuming compare to htop (maybe python's fault?)

**Comment by leonpano2006** [comment]
> Thank you I will take a look soon

No fixes?

**Comment by rbonghi** [comment]
This bug should be fixed from jetson-stats release **4.2.4**
to update:
```
sudo pip3 install -U jetson-stats
```
I close this issue, if this bug appear again, feel free to reopen it
