### ISSUE TITLE
`jetson.stats` is not a valid JSON string

### ISSUE THREAD

**Issue by sheldonmaschmeyer** [rbonghi/jetson_stats#398]
## Describe the bug

The `jetson.stats` is almost a valid JSON string but I need to make tweaks to the string for it to pass validation.

The following is done in JavaScript.

```
jetsonStats = jetsonStats.replace(/'/g, '"');
jetsonStats = jetsonStats.replace(/: datetime/g, ': "datetime');
jetsonStats = jetsonStats.replace(/\),/g, ')",');
JSON.parse(jetsonStats) // Success
```
## To Reproduce

1. 
```
jetson = jtop()
jetson.start()
print(jetson.stats)
jetson.close()
```
2. Copy string to an online validator such as https://jsonlint.com/
Notice it does not pass.

3. Pass string to Node.JS
```
jetsonStats = jetsonStats.replace(/'/g, '"');
jetsonStats = jetsonStats.replace(/: datetime/g, ': "datetime');
jetsonStats = jetsonStats.replace(/\),/g, ')",');
console.debug(jetsonStats)
JSON.parse(jetsonStats)
```
4. Notice it now passes the online validator https://jsonlint.com/

### Board
Ubuntu 18.04
jetson-stats==4.1.5

**Comment by sheldonmaschmeyer** [comment]
Found article https://www.influxdata.com/blog/nvidia-jetson-series-part-1-jetson-stats/

**Comment by rbonghi** [comment]
There is now a new function

```
jetson.json()
```

https://rnext.it/jetson_stats/reference/jtop.html#jtop.jtop.json

**Comment by SheldonWBM** [comment]
Thanks :+1:

**Comment by sheldonmaschmeyer** [comment]
Thanks :+1:
