### ISSUE TITLE
"Q" key to close

### ISSUE THREAD

**Issue by AlessioMorale** [rbonghi/jetson_stats#4]
Use "Q" key to close as it is standard among all *top utilities

**Comment by rbonghi** [comment]
Hi @AlessioMorale ,

Thank you for your issue, now you can close jtop with **Q** or **q** or **CTRL-C**

![image](https://user-images.githubusercontent.com/4551246/57196154-4a8cec00-6f5a-11e9-9b80-ab4fe30fe656.png)
