### ISSUE TITLE
jetson-stats not supported for [L4T 32.7.3]

### ISSUE THREAD

**Issue by Seunmul** [rbonghi/jetson_stats#403]
Please update jetson-stats with new jetpack

**Linux for Tegra**
 - L4T: 32.7.3

**Jetson-Stats**
 - Version: 3.1.4

My tx2 is updated to jetpack 32.7.2 to 32.7.3 and i think it works well in 32.7.2.
but the message show like..

```
[WARN] jetson-stats not supported for [L4T 32.7.3]
```

how can i solve it?

**Comment by maartenor** [comment]
https://github.com/rbonghi/jetson_stats/issues/410#issuecomment-1595276224

**Comment by rbonghi** [comment]
Hi @Seunmul, you are working with an old release of jetson-stats

Please update with the new version **4.2.4**
```
sudo pip3 install -U jetson-stats
```
