### ISSUE TITLE
/usr/local/lib/python3.6/dist-packages/services/jtop.service

### ISSUE THREAD

**Issue by Idowhat** [rbonghi/jetson_stats#404]
### Board

Output from `jetson_release -v`:

* jetson-stats version: [e.g. 1.8]
* P-Number: [e.g. pXXXX-XXXX]
* Module: [e.g. NVIDIA Jetson XXX]
* Jetpack: [e.g. 4.3]
* L4T: [e.g. 5.2.1]

### Log from jtop.service

Attach here the output from: `journalctl -u jtop.service -n 100 --no-pager`

### Log from jetson-stats installation

Attach here the output from: `sudo -H pip3 install --no-cache-dir -U jetson-stats`

**Comment by rbonghi** [comment]
Hi @Idowhat 

This bug is incomplete. Please open a new one describing your issue.
