### ISSUE TITLE
GUI compact engine page missing for [NVIDIA Jetson Orin Nano (Developer kit)]

### ISSUE THREAD

**Issue by bdherouville** [rbonghi/jetson_stats#405]
Please add a new jtop engine compact page for

### Board

 - Model: NVIDIA Orin Nano Developer Kit
 - 699-level Part Number: 699-13767-0005-300 K.2
 - P-Number: p3767-0005
 - Module: NVIDIA Jetson Orin Nano (Developer kit)
 - SoC: tegra23x
 - CUDA Arch BIN: 8.7
 - Codename: P3768
 - L4T: 35.3.1
 - Jetpack: 5.1.1

### jetson-stats

 - Version: 4.2.1

![image](https://user-images.githubusercontent.com/13697064/235792008-22ebea2b-2e6a-498a-a0bb-adff27d9ba98.png)

### Screenshot engine page

Screenshot page from jtop engine page attached

**Comment by rbonghi** [comment]
Fixed from release 4.2.2

```
sudo pip3 install -U jetson-stats
```
