### ISSUE TITLE
TensorRT had been installed in Clara AGX, but jtop cannot find it.

### ISSUE THREAD

**Issue by Rodeson** [rbonghi/jetson_stats#407]
My development platform is clara agx, ubuntu20.04 system.
I used the RTX6000 GPU and switched to ‘dgpu’ using nvgpuswitch.
When switching to dgpu, the TensorRT version cannot be viewed using jtop.
But it runs in python
1.import tensorrt
2.print(tensorrt.__version__)
TensorRT version 8.4.1.5 can be displayed normally.

**Comment by consolexinhun** [comment]
Maybe jtop only support for integrated GPU
