### ISSUE TITLE
can't install jetson-stats==4.2.1

### ISSUE THREAD

**Issue by consolexinhun** [rbonghi/jetson_stats#410]
## Describe the bug

I can not install jetson-stats==4.2.1 on my machine
## To Reproduce

when i run `sudo python3 -m pip install jetson-stats-4.2.1.tar.gz -v`，It gets stuck at "INFO:jtop.service: - ENABLE jtop.service"

## Screenshots

$ sudo python3 -m pip install jetson-stats-4.2.1.tar.gz -v
Using pip 22.2.2 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)
Processing ./jetson-stats-4.2.1.tar.gz
  Running command python setup.py egg_info
  running egg_info
  creating /tmp/pip-pip-egg-info-dca6h7vt/jetson_stats.egg-info
  writing /tmp/pip-pip-egg-info-dca6h7vt/jetson_stats.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-dca6h7vt/jetson_stats.egg-info/dependency_links.txt
  writing entry points to /tmp/pip-pip-egg-info-dca6h7vt/jetson_stats.egg-info/entry_points.txt
  writing requirements to /tmp/pip-pip-egg-info-dca6h7vt/jetson_stats.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-dca6h7vt/jetson_stats.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-dca6h7vt/jetson_stats.egg-info/SOURCES.txt'
  INFO:root:Generating grammar tables from /usr/lib/python3.8/lib2to3/Grammar.txt
  INFO:root:Generating grammar tables from /usr/lib/python3.8/lib2to3/PatternGrammar.txt
  reading manifest file '/tmp/pip-pip-egg-info-dca6h7vt/jetson_stats.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files found matching 'Dockerfile'
  warning: no previously-included files found matching '.dockerignore'
  no previously-included directories found matching 'tests'
  no previously-included directories found matching 'docs'
  no previously-included directories found matching 'examples'
  writing manifest file '/tmp/pip-pip-egg-info-dca6h7vt/jetson_stats.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done
Requirement already satisfied: smbus2 in /usr/local/lib/python3.8/dist-packages (from jetson-stats==4.2.1) (0.4.2)
Requirement already satisfied: distro in /usr/lib/python3/dist-packages (from jetson-stats==4.2.1) (1.4.0)
Building wheels for collected packages: jetson-stats
  Running command python setup.py bdist_wheel
  running bdist_wheel
  running build
  running build_py
  INFO:root:Generating grammar tables from /usr/lib/python3.8/lib2to3/Grammar.txt
  INFO:root:Generating grammar tables from /usr/lib/python3.8/lib2to3/PatternGrammar.txt
  creating build
  creating build/lib
  creating build/lib/jtop
  copying jtop/jetson_swap.py -> build/lib/jtop
  copying jtop/__main__.py -> build/lib/jtop
  copying jtop/jetson_config.py -> build/lib/jtop
  copying jtop/jetson_release.py -> build/lib/jtop
  copying jtop/terminal_colors.py -> build/lib/jtop
  copying jtop/__init__.py -> build/lib/jtop
  copying jtop/service.py -> build/lib/jtop
  copying jtop/jtop.py -> build/lib/jtop
  copying jtop/github.py -> build/lib/jtop
  creating build/lib/jtop/gui
  copying jtop/gui/jtopgui.py -> build/lib/jtop/gui
  copying jtop/gui/jtopguiconfig.py -> build/lib/jtop/gui
  copying jtop/gui/pgpu.py -> build/lib/jtop/gui
  copying jtop/gui/pall.py -> build/lib/jtop/gui
  copying jtop/gui/pcontrol.py -> build/lib/jtop/gui
  copying jtop/gui/pcpu.py -> build/lib/jtop/gui
  copying jtop/gui/pengine.py -> build/lib/jtop/gui
  copying jtop/gui/pinfo.py -> build/lib/jtop/gui
  copying jtop/gui/pmem.py -> build/lib/jtop/gui
  copying jtop/gui/__init__.py -> build/lib/jtop/gui
  creating build/lib/jtop/core
  copying jtop/core/processes.py -> build/lib/jtop/core
  copying jtop/core/config.py -> build/lib/jtop/core
  copying jtop/core/exceptions.py -> build/lib/jtop/core
  copying jtop/core/timer_reader.py -> build/lib/jtop/core
  copying jtop/core/nvpmodel.py -> build/lib/jtop/core
  copying jtop/core/jetson_clocks.py -> build/lib/jtop/core
  copying jtop/core/common.py -> build/lib/jtop/core
  copying jtop/core/fan.py -> build/lib/jtop/core
  copying jtop/core/gpu.py -> build/lib/jtop/core
  copying jtop/core/jetson_libraries.py -> build/lib/jtop/core
  copying jtop/core/engine.py -> build/lib/jtop/core
  copying jtop/core/tegra_parse.py -> build/lib/jtop/core
  copying jtop/core/command.py -> build/lib/jtop/core
  copying jtop/core/hardware.py -> build/lib/jtop/core
  copying jtop/core/__init__.py -> build/lib/jtop/core
  copying jtop/core/jetson_variables.py -> build/lib/jtop/core
  copying jtop/core/power.py -> build/lib/jtop/core
  copying jtop/core/temperature.py -> build/lib/jtop/core
  copying jtop/core/memory.py -> build/lib/jtop/core
  copying jtop/core/tegrastats.py -> build/lib/jtop/core
  copying jtop/core/cpu.py -> build/lib/jtop/core
  creating build/lib/jtop/gui/lib
  copying jtop/gui/lib/smallbutton.py -> build/lib/jtop/gui/lib
  copying jtop/gui/lib/linear_gauge.py -> build/lib/jtop/gui/lib
  copying jtop/gui/lib/chart.py -> build/lib/jtop/gui/lib
  copying jtop/gui/lib/colors.py -> build/lib/jtop/gui/lib
  copying jtop/gui/lib/common.py -> build/lib/jtop/gui/lib
  copying jtop/gui/lib/process_table.py -> build/lib/jtop/gui/lib
  copying jtop/gui/lib/__init__.py -> build/lib/jtop/gui/lib
  installing to build/bdist.linux-aarch64/wheel
  running install
  Install status:
   - [X] super_user
   - [ ] virtualenv
   - [ ] docker
  ERROR:jtop.service:Does not exist jetson_stats
  INFO:jtop.service:Found jtop.service
  INFO:jtop.service: - DISABLE jtop.service
  Removed /etc/systemd/system/multi-user.target.wants/jtop.service.
  INFO:jtop.service: - REMOVE jtop.service from /etc/systemd/system
  INFO:jtop.service: - Reload all daemons
  INFO:jtop.core.jetson_variables:Found jtop_env.sh
  INFO:jtop.core.jetson_variables: - Remove jtop_env.sh from /etc/profile.d/
  running install_lib
  creating build/bdist.linux-aarch64
  creating build/bdist.linux-aarch64/wheel
  creating build/bdist.linux-aarch64/wheel/jtop
  copying build/lib/jtop/jetson_swap.py -> build/bdist.linux-aarch64/wheel/jtop
  creating build/bdist.linux-aarch64/wheel/jtop/gui
  copying build/lib/jtop/gui/jtopgui.py -> build/bdist.linux-aarch64/wheel/jtop/gui
  copying build/lib/jtop/gui/jtopguiconfig.py -> build/bdist.linux-aarch64/wheel/jtop/gui
  copying build/lib/jtop/gui/pgpu.py -> build/bdist.linux-aarch64/wheel/jtop/gui
  copying build/lib/jtop/gui/pall.py -> build/bdist.linux-aarch64/wheel/jtop/gui
  copying build/lib/jtop/gui/pcontrol.py -> build/bdist.linux-aarch64/wheel/jtop/gui
  creating build/bdist.linux-aarch64/wheel/jtop/gui/lib
  copying build/lib/jtop/gui/lib/smallbutton.py -> build/bdist.linux-aarch64/wheel/jtop/gui/lib
  copying build/lib/jtop/gui/lib/linear_gauge.py -> build/bdist.linux-aarch64/wheel/jtop/gui/lib
  copying build/lib/jtop/gui/lib/chart.py -> build/bdist.linux-aarch64/wheel/jtop/gui/lib
  copying build/lib/jtop/gui/lib/colors.py -> build/bdist.linux-aarch64/wheel/jtop/gui/lib
  copying build/lib/jtop/gui/lib/common.py -> build/bdist.linux-aarch64/wheel/jtop/gui/lib
  copying build/lib/jtop/gui/lib/process_table.py -> build/bdist.linux-aarch64/wheel/jtop/gui/lib
  copying build/lib/jtop/gui/lib/__init__.py -> build/bdist.linux-aarch64/wheel/jtop/gui/lib
  copying build/lib/jtop/gui/pcpu.py -> build/bdist.linux-aarch64/wheel/jtop/gui
  copying build/lib/jtop/gui/pengine.py -> build/bdist.linux-aarch64/wheel/jtop/gui
  copying build/lib/jtop/gui/pinfo.py -> build/bdist.linux-aarch64/wheel/jtop/gui
  copying build/lib/jtop/gui/pmem.py -> build/bdist.linux-aarch64/wheel/jtop/gui
  copying build/lib/jtop/gui/__init__.py -> build/bdist.linux-aarch64/wheel/jtop/gui
  creating build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/processes.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/config.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/exceptions.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/timer_reader.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/nvpmodel.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/jetson_clocks.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/common.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/fan.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/gpu.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/jetson_libraries.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/engine.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/tegra_parse.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/command.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/hardware.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/__init__.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/jetson_variables.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/power.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/temperature.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/memory.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/tegrastats.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/cpu.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/__main__.py -> build/bdist.linux-aarch64/wheel/jtop
  copying build/lib/jtop/jetson_config.py -> build/bdist.linux-aarch64/wheel/jtop
  copying build/lib/jtop/jetson_release.py -> build/bdist.linux-aarch64/wheel/jtop
  copying build/lib/jtop/terminal_colors.py -> build/bdist.linux-aarch64/wheel/jtop
  copying build/lib/jtop/__init__.py -> build/bdist.linux-aarch64/wheel/jtop
  copying build/lib/jtop/service.py -> build/bdist.linux-aarch64/wheel/jtop
  copying build/lib/jtop/jtop.py -> build/bdist.linux-aarch64/wheel/jtop
  copying build/lib/jtop/github.py -> build/bdist.linux-aarch64/wheel/jtop
  running install_data
  creating build/bdist.linux-aarch64/wheel/jetson_stats-4.2.1.data
  creating build/bdist.linux-aarch64/wheel/jetson_stats-4.2.1.data/data
  creating build/bdist.linux-aarch64/wheel/jetson_stats-4.2.1.data/data/jetson_stats
  copying services/jtop.service -> build/bdist.linux-aarch64/wheel/jetson_stats-4.2.1.data/data/jetson_stats
  copying scripts/jtop_env.sh -> build/bdist.linux-aarch64/wheel/jetson_stats-4.2.1.data/data/jetson_stats
  running install_egg_info
  running egg_info
  writing jetson_stats.egg-info/PKG-INFO
  writing dependency_links to jetson_stats.egg-info/dependency_links.txt
  writing entry points to jetson_stats.egg-info/entry_points.txt
  writing requirements to jetson_stats.egg-info/requires.txt
  writing top-level names to jetson_stats.egg-info/top_level.txt
  reading manifest file 'jetson_stats.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files found matching 'Dockerfile'
  warning: no previously-included files found matching '.dockerignore'
  no previously-included directories found matching 'tests'
  no previously-included directories found matching 'docs'
  no previously-included directories found matching 'examples'
  writing manifest file 'jetson_stats.egg-info/SOURCES.txt'
  Copying jetson_stats.egg-info to build/bdist.linux-aarch64/wheel/jetson_stats-4.2.1-py3.8.egg-info
  running install_scripts
  INFO:jtop.core.jetson_variables:Install jtop_env.sh variables
  INFO:jtop.core.jetson_variables: - COPYING jtop_env.sh -> /etc/profile.d/jtop_env.sh
  INFO:jtop.service:Install jtop.service
  INFO:jtop.service: - COPYING jtop.service -> /etc/systemd/system/jtop.service
  INFO:jtop.service: - Reload all daemons
  INFO:jtop.service: - ENABLE jtop.service

## Expected behavior

Please explain the reason for this and install it successfully

### Log from jetson-stats installation

Attach here the output from: `sudo -H pip3 install --no-cache-dir -U jetson-stats`

**Comment by consolexinhun** [comment]
on another machine, it can install jetson-stats==4.2.1 but can not start jtop service

```
➜  ~ pip -V          
pip 20.2.2 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
➜  ~ pip list | grep jetson-stats
jetson-stats                  4.2.1
WARNING: You are using pip version 20.2.2; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
➜  ~ sudo systemctl restart jtop
<It gets stuck at here>
```

**Comment by maartenor** [comment]
Similar issue here. When attempting to run `sudo systemctl restart jtop.service` I receive no messages. However trying to run `sudo /usr/local/bin/jtop` results in the 'advice' to Please run `sudo systemctl restart jtop.service` Looping from here.

Checking logs `sudo journalctl -b -u jtop.service` shows the error logs that `smbus2` module cannot be found:

> Jun 16 20:10:34 JetsonTX2-3 systemd[1]: jtop.service: Service hold-off time over, scheduling restart.
> Jun 16 20:10:34 JetsonTX2-3 systemd[1]: jtop.service: Scheduled restart job, restart counter is at 167.
> Jun 16 20:10:34 JetsonTX2-3 systemd[1]: Stopped jtop service.
> Jun 16 20:10:34 JetsonTX2-3 systemd[1]: Started jtop service.
> Jun 16 20:10:35 JetsonTX2-3 jtop[15911]: Traceback (most recent call last):
> Jun 16 20:10:35 JetsonTX2-3 jtop[15911]:   File "/usr/local/bin/jtop", line 6, in <module>
> Jun 16 20:10:35 JetsonTX2-3 jtop[15911]:     from pkg_resources import load_entry_point
> Jun 16 20:10:35 JetsonTX2-3 jtop[15911]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
> Jun 16 20:10:35 JetsonTX2-3 jtop[15911]:     @_call_aside
> Jun 16 20:10:35 JetsonTX2-3 jtop[15911]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
> Jun 16 20:10:35 JetsonTX2-3 jtop[15911]:     f(*args, **kwargs)
> Jun 16 20:10:35 JetsonTX2-3 jtop[15911]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
> Jun 16 20:10:35 JetsonTX2-3 jtop[15911]:     working_set = WorkingSet._build_master()
> Jun 16 20:10:35 JetsonTX2-3 jtop[15911]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
> Jun 16 20:10:35 JetsonTX2-3 jtop[15911]:     ws.require(__requires__)
> Jun 16 20:10:35 JetsonTX2-3 jtop[15911]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
> Jun 16 20:10:35 JetsonTX2-3 jtop[15911]:     needed = self.resolve(parse_requirements(requirements))
> Jun 16 20:10:35 JetsonTX2-3 jtop[15911]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
> Jun 16 20:10:35 JetsonTX2-3 jtop[15911]:     raise DistributionNotFound(req, requirers)
> Jun 16 20:10:35 JetsonTX2-3 jtop[15911]: pkg_resources.DistributionNotFound: The 'smbus2' distribution was not found and is required by jetson-stats
> Jun 16 20:10:35 JetsonTX2-3 systemd[1]: jtop.service: Main process exited, code=exited, status=1/FAILURE
> Jun 16 20:10:35 JetsonTX2-3 systemd[1]: jtop.service: Failed with result 'exit-code'.

The smbus2 module for python is installed in ` /home/<user>/.local/lib/python3.6/site-packages` but not found.
