### ISSUE TITLE
Uninstall instructions

### ISSUE THREAD

**Issue by AndreaCogliati** [rbonghi/jetson_stats#434]
How to perform a full uninstall? I tried `sudo pip3 uninstall jetson-stats`, however, I still see leftover files around the file system; e.g., `jtop.service` in `/etc/systemd/system`. It looks like there was an uninstall page in the Wiki but it's gone now.

**Comment by rbonghi** [comment]
Hi @AndreaCogliati 

I apologize for the late reply. I'll add a page on the documentation for a correct uninstall of jetson-stats.
I'll keep you posted

**Comment by rbonghi** [comment]
Now on page https://rnext.it/jetson_stats/jtop/jtop.html#uninstall
