### ISSUE TITLE
jetson-stats not supported for [L4T 35.4.1]

### ISSUE THREAD

**Issue by BartoszKossowski** [rbonghi/jetson_stats#435]
Please update jetson-stats with new jetpack

### Linux for Tegra

 - L4T: 35.4.1

### Jetson-Stats

 - Version: 4.2.2
From terminal:
**[WARN] jetson-stats not supported for [L4T 35.4.1]**

**Comment by dudo** [comment]
Any idea on when you'll have a chance to update this?

**Comment by atinfinity** [comment]
I add the following value to [jtop/core/jetson_variables.py](https://github.com/rbonghi/jetson_stats/blob/4.2.2/jtop/core/jetson_variables.py#L43).

```
"35.4.1": "5.1.2",
```

As a result, I can show the information of L4T 35.4.1.

### jetson_release

![updated_jetson_release](https://github.com/rbonghi/jetson_stats/assets/2630323/317a8e9e-048d-49a2-8836-e6f6a6116652)

### jtop

If you changed code, you need to restart `jtop` service.

![updated_jtop](https://github.com/rbonghi/jetson_stats/assets/2630323/fa00468f-fabf-49c0-b221-cafc51a72c5f)

**Comment by rbonghi** [comment]
Fixed with the new release. Please update to **4.2.3**
```
sudo pip3 install -U jetson-stats
```
