### ISSUE TITLE
I want to know what these parameters mean? 

### ISSUE THREAD

**Issue by Washington-DC** [rbonghi/jetson_stats#463]
I want to know what these parameters mean? Because I haven't found it in the documents or wiki, such as EMC, VIC, SE, APE, PVA, Tboard, Tdiode, Tj, VIN, and does this CPU usage refer to the usage of a single core? Thank you, I'm a bit confused

**Comment by rbonghi** [comment]
Hi @Washington-DC 

The output you read from jtop is automatically generated from the NVIDIA Jetson output.
Please refer to the [official NVIDIA documentation](https://docs.nvidia.com/jetson/archives/r36.2/DeveloperGuide/SD/PlatformPowerAndPerformance/JetsonOrinNanoSeriesJetsonOrinNxSeriesAndJetsonAgxOrinSeries.html?highlight=temperature#bsp-specific-thermal-zones)

Also you can find a link to the NVIDIA documentation from [jtop.temperature](https://rnext.it/jetson_stats/reference/jtop.html#jtop.jtop.temperature)
