### ISSUE TITLE
Jtop service not installed correctly on Jetson Nano

### ISSUE THREAD

**Issue by halsimov** [rbonghi/jetson_stats#466]
## Describe the bug

jtop is installed but do act as if the jtop.service is not enabled

## To Reproduce

1. Install jtop using ` sudo pip3 install  -U jetson-stats`
2. reboot
3. Run jtop
4. See the following error
```
The jtop.service is not active. Please run:
sudo systemctl restart jtop.service
```

## Expected behavior

I want to be able to actually run jtop

## Additional context

I tried to reload service but it is not found. It does seems that service and setup config files have been installed in a wrong folder.

### Board

<details>
<summary><code>uname -a</code></summary>
<pre>
Linux jetson-nano-1-108 4.9.140-tegra #1 SMP PREEMPT Tue Oct 27 21:02:37 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux
</pre>
</details>

<details>
<summary><code>jetson_release -v</code></summary>
<pre>
Software part of jetson-stats 4.2.3 - (c) 2023, Raffaello Bonghi
Model: NVIDIA Jetson Nano Developer Kit - Jetpack 4.4.1 [L4T 32.4.4]
NV Power Mode[1]: 5W
Serial Number: [XXX Show with: jetson_release -s XXX]
Hardware:
 - P-Number: p3448-0000
 - BoardIDs: p3448
 - Module: NVIDIA Jetson Nano (4 GB ram)
 - SoC: tegra210
 - CUDA Arch BIN: 5.3
 - Codename: Porg
Platform:
 - Machine: aarch64
 - System: Linux
 - Distribution: Ubuntu 18.04 Bionic Beaver
 - Release: 4.9.140-tegra
 - Python: 3.6.9
jtop:
 - Version: 4.2.3
 - Service: Active
Libraries:
 - CUDA: 10.2.89
 - cuDNN: 8.0.0.180
 - TensorRT: 7.1.3.0
 - VPI: 4.4.1
 - Vulkan: 1.2.70
 - OpenCV: 4.1.1 - with CUDA: NO
</pre>
</details>

### Log from jtop.service

<details>
<summary><code>journalctl -u jtop.service -n 100 --no-pager</code></summary>
<pre>
-- Logs begin at Wed 2023-11-15 11:33:34 CET, end at Wed 2023-11-15 18:02:27 CET. --
Nov 15 18:01:04 jetson-nano-1-108 systemd[1]: Stopped jtop service.
Nov 15 18:01:04 jetson-nano-1-108 systemd[1]: Started jtop service.
Nov 15 18:01:06 jetson-nano-1-108 jtop[12031]: Traceback (most recent call last):
Nov 15 18:01:06 jetson-nano-1-108 jtop[12031]:   File "/usr/local/bin/jtop", line 11, in <module>
Nov 15 18:01:06 jetson-nano-1-108 jtop[12031]:     load_entry_point('jetson-stats==4.2.3', 'console_scripts', 'jtop')()
Nov 15 18:01:06 jetson-nano-1-108 jtop[12031]:   File "/usr/local/lib/python3.6/dist-packages/jtop/__main__.py", line 98, in main
Nov 15 18:01:06 jetson-nano-1-108 jtop[12031]:     locale.setlocale(locale.LC_ALL, '')
Nov 15 18:01:06 jetson-nano-1-108 jtop[12031]:   File "/usr/lib/python3.6/locale.py", line 598, in setlocale
Nov 15 18:01:06 jetson-nano-1-108 jtop[12031]:     return _setlocale(category, locale)
Nov 15 18:01:06 jetson-nano-1-108 jtop[12031]: locale.Error: unsupported locale setting
Nov 15 18:01:06 jetson-nano-1-108 systemd[1]: jtop.service: Main process exited, code=exited, status=1/FAILURE
Nov 15 18:01:06 jetson-nano-1-108 systemd[1]: jtop.service: Failed with result 'exit-code'.
Nov 15 18:01:16 jetson-nano-1-108 systemd[1]: jtop.service: Service hold-off time over, scheduling restart.
Nov 15 18:01:16 jetson-nano-1-108 systemd[1]: jtop.service: Scheduled restart job, restart counter is at 1978.
Nov 15 18:01:16 jetson-nano-1-108 systemd[1]: Stopped jtop service.
Nov 15 18:01:16 jetson-nano-1-108 systemd[1]: Started jtop service.
Nov 15 18:01:18 jetson-nano-1-108 jtop[12096]: Traceback (most recent call last):
Nov 15 18:01:18 jetson-nano-1-108 jtop[12096]:   File "/usr/local/bin/jtop", line 11, in <module>
Nov 15 18:01:18 jetson-nano-1-108 jtop[12096]:     load_entry_point('jetson-stats==4.2.3', 'console_scripts', 'jtop')()
Nov 15 18:01:18 jetson-nano-1-108 jtop[12096]:   File "/usr/local/lib/python3.6/dist-packages/jtop/__main__.py", line 98, in main
Nov 15 18:01:18 jetson-nano-1-108 jtop[12096]:     locale.setlocale(locale.LC_ALL, '')
Nov 15 18:01:18 jetson-nano-1-108 jtop[12096]:   File "/usr/lib/python3.6/locale.py", line 598, in setlocale
Nov 15 18:01:18 jetson-nano-1-108 jtop[12096]:     return _setlocale(category, locale)
Nov 15 18:01:18 jetson-nano-1-108 jtop[12096]: locale.Error: unsupported locale setting
Nov 15 18:01:18 jetson-nano-1-108 systemd[1]: jtop.service: Main process exited, code=exited, status=1/FAILURE
Nov 15 18:01:18 jetson-nano-1-108 systemd[1]: jtop.service: Failed with result 'exit-code'.
Nov 15 18:01:28 jetson-nano-1-108 systemd[1]: jtop.service: Service hold-off time over, scheduling restart.
Nov 15 18:01:28 jetson-nano-1-108 systemd[1]: jtop.service: Scheduled restart job, restart counter is at 1979.
Nov 15 18:01:28 jetson-nano-1-108 systemd[1]: Stopped jtop service.
Nov 15 18:01:28 jetson-nano-1-108 systemd[1]: Started jtop service.
Nov 15 18:01:29 jetson-nano-1-108 jtop[12160]: Traceback (most recent call last):
Nov 15 18:01:29 jetson-nano-1-108 jtop[12160]:   File "/usr/local/bin/jtop", line 11, in <module>
Nov 15 18:01:29 jetson-nano-1-108 jtop[12160]:     load_entry_point('jetson-stats==4.2.3', 'console_scripts', 'jtop')()
Nov 15 18:01:29 jetson-nano-1-108 jtop[12160]:   File "/usr/local/lib/python3.6/dist-packages/jtop/__main__.py", line 98, in main
Nov 15 18:01:29 jetson-nano-1-108 jtop[12160]:     locale.setlocale(locale.LC_ALL, '')
Nov 15 18:01:29 jetson-nano-1-108 jtop[12160]:   File "/usr/lib/python3.6/locale.py", line 598, in setlocale
Nov 15 18:01:29 jetson-nano-1-108 jtop[12160]:     return _setlocale(category, locale)
Nov 15 18:01:29 jetson-nano-1-108 jtop[12160]: locale.Error: unsupported locale setting
Nov 15 18:01:30 jetson-nano-1-108 systemd[1]: jtop.service: Main process exited, code=exited, status=1/FAILURE
Nov 15 18:01:30 jetson-nano-1-108 systemd[1]: jtop.service: Failed with result 'exit-code'.
Nov 15 18:01:40 jetson-nano-1-108 systemd[1]: jtop.service: Service hold-off time over, scheduling restart.
Nov 15 18:01:40 jetson-nano-1-108 systemd[1]: jtop.service: Scheduled restart job, restart counter is at 1980.
Nov 15 18:01:40 jetson-nano-1-108 systemd[1]: Stopped jtop service.
Nov 15 18:01:40 jetson-nano-1-108 systemd[1]: Started jtop service.
Nov 15 18:01:41 jetson-nano-1-108 jtop[12227]: Traceback (most recent call last):
Nov 15 18:01:41 jetson-nano-1-108 jtop[12227]:   File "/usr/local/bin/jtop", line 11, in <module>
Nov 15 18:01:41 jetson-nano-1-108 jtop[12227]:     load_entry_point('jetson-stats==4.2.3', 'console_scripts', 'jtop')()
Nov 15 18:01:41 jetson-nano-1-108 jtop[12227]:   File "/usr/local/lib/python3.6/dist-packages/jtop/__main__.py", line 98, in main
Nov 15 18:01:41 jetson-nano-1-108 jtop[12227]:     locale.setlocale(locale.LC_ALL, '')
Nov 15 18:01:41 jetson-nano-1-108 jtop[12227]:   File "/usr/lib/python3.6/locale.py", line 598, in setlocale
Nov 15 18:01:41 jetson-nano-1-108 jtop[12227]:     return _setlocale(category, locale)
Nov 15 18:01:41 jetson-nano-1-108 jtop[12227]: locale.Error: unsupported locale setting
Nov 15 18:01:41 jetson-nano-1-108 systemd[1]: jtop.service: Main process exited, code=exited, status=1/FAILURE
Nov 15 18:01:41 jetson-nano-1-108 systemd[1]: jtop.service: Failed with result 'exit-code'.
Nov 15 18:01:51 jetson-nano-1-108 systemd[1]: jtop.service: Service hold-off time over, scheduling restart.
Nov 15 18:01:51 jetson-nano-1-108 systemd[1]: jtop.service: Scheduled restart job, restart counter is at 1981.
Nov 15 18:01:51 jetson-nano-1-108 systemd[1]: Stopped jtop service.
Nov 15 18:01:51 jetson-nano-1-108 systemd[1]: Started jtop service.
Nov 15 18:01:53 jetson-nano-1-108 jtop[12289]: Traceback (most recent call last):
Nov 15 18:01:53 jetson-nano-1-108 jtop[12289]:   File "/usr/local/bin/jtop", line 11, in <module>
Nov 15 18:01:53 jetson-nano-1-108 jtop[12289]:     load_entry_point('jetson-stats==4.2.3', 'console_scripts', 'jtop')()
Nov 15 18:01:53 jetson-nano-1-108 jtop[12289]:   File "/usr/local/lib/python3.6/dist-packages/jtop/__main__.py", line 98, in main
Nov 15 18:01:53 jetson-nano-1-108 jtop[12289]:     locale.setlocale(locale.LC_ALL, '')
Nov 15 18:01:53 jetson-nano-1-108 jtop[12289]:   File "/usr/lib/python3.6/locale.py", line 598, in setlocale
Nov 15 18:01:53 jetson-nano-1-108 jtop[12289]:     return _setlocale(category, locale)
Nov 15 18:01:53 jetson-nano-1-108 jtop[12289]: locale.Error: unsupported locale setting
Nov 15 18:01:53 jetson-nano-1-108 systemd[1]: jtop.service: Main process exited, code=exited, status=1/FAILURE
Nov 15 18:01:53 jetson-nano-1-108 systemd[1]: jtop.service: Failed with result 'exit-code'.
Nov 15 18:02:03 jetson-nano-1-108 systemd[1]: jtop.service: Service hold-off time over, scheduling restart.
Nov 15 18:02:03 jetson-nano-1-108 systemd[1]: jtop.service: Scheduled restart job, restart counter is at 1982.
Nov 15 18:02:03 jetson-nano-1-108 systemd[1]: Stopped jtop service.
Nov 15 18:02:03 jetson-nano-1-108 systemd[1]: Started jtop service.
Nov 15 18:02:05 jetson-nano-1-108 jtop[12356]: Traceback (most recent call last):
Nov 15 18:02:05 jetson-nano-1-108 jtop[12356]:   File "/usr/local/bin/jtop", line 11, in <module>
Nov 15 18:02:05 jetson-nano-1-108 jtop[12356]:     load_entry_point('jetson-stats==4.2.3', 'console_scripts', 'jtop')()
Nov 15 18:02:05 jetson-nano-1-108 jtop[12356]:   File "/usr/local/lib/python3.6/dist-packages/jtop/__main__.py", line 98, in main
Nov 15 18:02:05 jetson-nano-1-108 jtop[12356]:     locale.setlocale(locale.LC_ALL, '')
Nov 15 18:02:05 jetson-nano-1-108 jtop[12356]:   File "/usr/lib/python3.6/locale.py", line 598, in setlocale
Nov 15 18:02:05 jetson-nano-1-108 jtop[12356]:     return _setlocale(category, locale)
Nov 15 18:02:05 jetson-nano-1-108 jtop[12356]: locale.Error: unsupported locale setting
Nov 15 18:02:05 jetson-nano-1-108 systemd[1]: jtop.service: Main process exited, code=exited, status=1/FAILURE
Nov 15 18:02:05 jetson-nano-1-108 systemd[1]: jtop.service: Failed with result 'exit-code'.
Nov 15 18:02:15 jetson-nano-1-108 systemd[1]: jtop.service: Service hold-off time over, scheduling restart.
Nov 15 18:02:15 jetson-nano-1-108 systemd[1]: jtop.service: Scheduled restart job, restart counter is at 1983.
Nov 15 18:02:15 jetson-nano-1-108 systemd[1]: Stopped jtop service.
Nov 15 18:02:15 jetson-nano-1-108 systemd[1]: Started jtop service.
Nov 15 18:02:16 jetson-nano-1-108 jtop[12418]: Traceback (most recent call last):
Nov 15 18:02:16 jetson-nano-1-108 jtop[12418]:   File "/usr/local/bin/jtop", line 11, in <module>
Nov 15 18:02:16 jetson-nano-1-108 jtop[12418]:     load_entry_point('jetson-stats==4.2.3', 'console_scripts', 'jtop')()
Nov 15 18:02:16 jetson-nano-1-108 jtop[12418]:   File "/usr/local/lib/python3.6/dist-packages/jtop/__main__.py", line 98, in main
Nov 15 18:02:16 jetson-nano-1-108 jtop[12418]:     locale.setlocale(locale.LC_ALL, '')
Nov 15 18:02:16 jetson-nano-1-108 jtop[12418]:   File "/usr/lib/python3.6/locale.py", line 598, in setlocale
Nov 15 18:02:16 jetson-nano-1-108 jtop[12418]:     return _setlocale(category, locale)
Nov 15 18:02:16 jetson-nano-1-108 jtop[12418]: locale.Error: unsupported locale setting
Nov 15 18:02:17 jetson-nano-1-108 systemd[1]: jtop.service: Main process exited, code=exited, status=1/FAILURE
Nov 15 18:02:17 jetson-nano-1-108 systemd[1]: jtop.service: Failed with result 'exit-code'.
Nov 15 18:02:27 jetson-nano-1-108 systemd[1]: jtop.service: Service hold-off time over, scheduling restart.
Nov 15 18:02:27 jetson-nano-1-108 systemd[1]: jtop.service: Scheduled restart job, restart counter is at 1984.
Nov 15 18:02:27 jetson-nano-1-108 systemd[1]: Stopped jtop service.
Nov 15 18:02:27 jetson-nano-1-108 systemd[1]: Started jtop service.
</pre>
</details>

### Log from jetson-stats installation

<details>
<summary><code>sudo -H pip3 install --no-cache-dir -U jetson-stats</code></summary>
<pre>
Collecting jetson-stats
  Downloading https://files.pythonhosted.org/packages/83/7d/ee33e4ae4f02bc4b105f2efafde908ff98fe256b913093b4918802d7b7a5/jetson-stats-4.2.3.tar.gz (115kB)
    100% |████████████████████████████████| 122kB 6.8MB/s 
Requirement already up-to-date: distro in /usr/local/lib/python3.6/dist-packages (from jetson-stats)
Requirement already up-to-date: smbus2 in /usr/local/lib/python3.6/dist-packages (from jetson-stats)
Installing collected packages: jetson-stats
  Running setup.py install for jetson-stats ... done
</pre>
</details>

**Comment by telemething** [comment]
also happening on Orin AGX

**Comment by rbonghi** [comment]
Hi @halsimov I see where the bug come from, I will fix soon as possible

**Comment by rbonghi** [comment]
Hi @mariobaldini 

Thank you for your post. I will fix this bug in the next release of Jetson-stats.

About nvpmodel I'll take a look soon
