### ISSUE TITLE
jetson-stats not getting installed on Host machine

### ISSUE THREAD

**Issue by kAvatar** [rbonghi/jetson_stats#468]
I have managed to successfully install jetson-stats on NVIDIA Orin but now I am trying to install it on my host machine which is MacBook .I am getting following error.

<img width="1450" alt="image" src="https://github.com/rbonghi/jetson_stats/assets/33368663/2511e390-7ef9-4cdd-a4c1-4d8ce44f6a5e">

Steps to reproduce:
-git clone https://github.com/rbonghi/jetson_stats/
-cd jetson-stats
-Create Virtualenv
-Activate Virtualenv
-sudo python3 -m pip install -U  jetson-stats

I wonder if the library is compatible with Mac or not.

**Comment by rbonghi** [comment]
Hi @kAvatar 

jetson-stats works only on NVIDIA Jetson devices (soon on Linux devices)

right now, Mac is not compatible
