### ISSUE TITLE
Error regarding memory usage display in Jtop 4.2.3

### ISSUE THREAD

**Issue by vesselofgod** [rbonghi/jetson_stats#469]
## Describe the bug

There's an error where the memory usage notation changes from 900Mib to 1100Mib (so if unit changes to 1.1 Gib) it's displayed as 100Mib.

## To Reproduce

It doesn't always happen, but it occurs when the memory usage unit changes on the Jetson.
(The above explanation is the most representative example)
The easiest way to reproduce the bug is to allocate resources without specifying a memory limit in the resources field.

<img width="400" alt="image" src="https://github.com/rbonghi/jetson_stats/assets/18081105/6aa6f253-5afd-48e4-ac05-99414d329570">

## Expected behavior

In the example above, it is displayed as 100MiB when checked through ```jtop / free -h```, but when checking ```free -h``` in Linux, it is using 1.1GiB.

### Board

Output from `jetson_release -v`:

![Untitled (5)](https://github.com/rbonghi/jetson_stats/assets/18081105/fc49052d-c378-4041-a644-6dfa990e82e5)

### Log from jetson-stats installation

Attach here the output from: `sudo -H pip3 install --no-cache-dir -U jetson-stats`

<img width="1004" alt="Untitled (6)" src="https://github.com/rbonghi/jetson_stats/assets/18081105/5cf1f254-bc91-416a-8d19-fadee3da8a97">

**Comment by artur-ag** [comment]
Seems to be the same as https://github.com/rbonghi/jetson_stats/issues/413.

**Comment by rbonghi** [comment]
I am closing this issue.
Please respond directly to the other issue.
