### ISSUE TITLE
[WARN] jetson-stats not supported for [L4T 35.5.0]

### ISSUE THREAD

**Issue by Jen-Hung-Ho** [rbonghi/jetson_stats#495]
## Describe the bug
Jetop not detect jetpack version 5.1.3 on Jetson Orion Nano

## To Reproduce
Install Jetpack version 5.1.3 

1. run sudo jtop.  [see screenshost]
2. then quit jtop  
3. jetbot@ubuntu:~$ sudo jtop
[WARN] jetson-stats not supported for [L4T 35.5.0]
  Please, try: sudo pip3 install -U jetson-stats or
  open a Github issue (press CTRL + Click)

jetbot@ubuntu:~$ apt-cache show nvidia-jetpack
Package: nvidia-jetpack
Version: 5.1.3-b29
Architecture: arm64
Maintainer: NVIDIA Corporation

## Screenshots
![Screenshot 2024-02-22 224234](https://github.com/rbonghi/jetson_stats/assets/23567543/7b899eed-de2f-4824-90a5-6829253828b6)
![Screenshot 2024-02-22 224359](https://github.com/rbonghi/jetson_stats/assets/23567543/5166a9a7-8ce5-4d04-bc02-4c02970d70b3)

**Comment by Jen-Hung-Ho** [comment]
Reference 
[Jetpack Not Detected Or Missing On Jetson Orin Nano](https://forums.developer.nvidia.com/t/jetpack-not-detected-or-missing-on-jetson-orin-nano/263150)
Down grade to JetPack 5.1.2.  L4t: 35.4.3 fix the issue.

**Comment by rbonghi** [comment]
This bug will be fixed later today

**Comment by rbonghi** [comment]
Fixed with the new release. Please update to **4.2.7**

```
sudo pip3 install -U jetson-stats
```
