### ISSUE TITLE
"Flickering" values

### ISSUE THREAD

**Issue by AlessioMorale** [rbonghi/jetson_stats#5]
Values are updated pretty often on screen (at least using ssh) and they are sometimes hard to read.
A suggestion may be to perform a moving average of all values in background and show the averaged result once/twice per second.

**Comment by rbonghi** [comment]
Hi @AlessioMorale,

Now the interface is without flickering and is more stable than before.
The GUI controller is completely rewritten and I change the refresh rate from 100hz to 500hz to decrease the process consumption.

If you want change the refresh rate you can set:
```
jtop -r RATE
```
where RATE is the new refresh rate in ms
