### ISSUE TITLE
jetson-stats not supported for [L4T 35.5.0]

### ISSUE THREAD

**Issue by jeonsion** [rbonghi/jetson_stats#503]
Please update jetson-stats with new jetpack

### Linux for Tegra

 - L4T: 35.5.0

### Jetson-Stats

 - Version: 4.2.6

i'm using jetson agx xavier

**Comment by rbonghi** [comment]
Fixed with the new release. Please update to **4.2.7**

```
sudo pip3 install -U jetson-stats
```
