### ISSUE TITLE
Hardware Missing: p3767-0003

### ISSUE THREAD

**Issue by ClemensHasiner** [rbonghi/jetson_stats#514]
Please update jetson-stats with this board

### Board

 - Model: NVIDIA Orin Nano Developer Kit
 - 699-level Part Number: 699-13767-0003-300 L.3
 - P-Number: p3767-0003
 - Module: NVIDIA Jetson Orin Nano (8GB ram)
 - SoC: tegra23x
 - CUDA Arch BIN: 8.7
 - Codename: P3768
 - L4T: 35.3.1
 - Jetpack: 5.1.1

### Jetson-Stats

 - Version: 4.2.7

### RAW Data

[jtop-error.log](https://github.com/rbonghi/jetson_stats/files/15009396/jtop-error.log)

File from `--error-log` attached

**Comment by rbonghi** [comment]
real strange bug.
Reading your board output seems the board is detected.

I keep you posted if I figure out the reason of this board missing
