### ISSUE TITLE
Hardware Missing: pÿÿÿÿ-ÿÿÿÿ

### ISSUE THREAD

**Issue by mingx9527** [rbonghi/jetson_stats#515]
Please update jetson-stats with this board

### Board

 - Model: lanai-3636
 - 699-level Part Number: ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
 - P-Number: pÿÿÿÿ-ÿÿÿÿ
 - BoardIDs: p3636-0001-A0
 - Module: **MISSING**
 - SoC: tegra186
 - CUDA Arch BIN: 6.2
 - Codename: Lanai
 - L4T: 32.7.1
 - Jetpack: 4.6.1

### Jetson-Stats

 - Version: 4.2.7

### RAW Data

File from `--error-log` attached

**Comment by rbonghi** [comment]
Hi @mingx9527 

can you please share the output from `jtop --error-log`
