### ISSUE TITLE
Jetpack missing [JP6.0 - L4T 36.3]

### ISSUE THREAD

**Issue by lakshanthad** [rbonghi/jetson_stats#517]
Hello,

Please update jetson-stats with new JetPack 6.0 (L4T 36.3)

Thanks.

![image](https://github.com/rbonghi/jetson_stats/assets/20147381/e989299b-bb21-4d31-a99e-e5fa5984d5fd)

**Comment by rbonghi** [comment]
Fixed with release **4.2.8**

```
sudo pip3 install -U jetson-stats
```
