### ISSUE TITLE
does it support execution jtop without elevation to sudo?

### ISSUE THREAD

**Issue by AndreV84** [rbonghi/jetson_stats#52]
does it support execution jtop / jetson-stats without elevation to sudo?

**Comment by rbonghi** [comment]
Hi @AndreV84 ,

jtop works without sudo, but not all features are available.
jtop read some information from tegrastats and jetson_clocks to build all menu.

tegrastats and jetson_clocks as well, require to read all information the sudo elevation.

Without use jtop, the only output available is like this picture
![image](https://user-images.githubusercontent.com/4551246/78451503-e26ceb80-767d-11ea-8e42-38d4c57a160f.png)

At this time I didn't find any other solution to read the same data without sudo.

**Comment by AndreV84** [comment]
Thank you for your response!

**Comment by rbonghi** [comment]
You are welcome! :+1:

**Comment by rbonghi** [comment]
I’m completely rewriting jtop to works without sudo. I think in 1 or 2 weekS I will release the first release candidate to test.

I will write here a new message when you can start to try.
