### ISSUE TITLE
Jtop Error only one module

### ISSUE THREAD

**Issue by VOCA-L** [rbonghi/jetson_stats#534]
## Describe the bug

I am using 5. Orin NX 8G model

It says that flashing is completed successfully in sdkmanager.

However, jtop fails like below only on one module. (screen shot)

I am using the same nvme by copying it, and I am curious why only one is showing this error.

note : 

## Screenshots

![image](https://github.com/rbonghi/jetson_stats/assets/110345669/9b572a06-8a2b-4b3f-a5e3-61c651730df3)

### Board
![image](https://github.com/rbonghi/jetson_stats/assets/110345669/c5683c49-88a7-4ba7-b805-229d60288e07)

**Comment by evildeeds** [comment]
Looks like the same backtrace as #492

**Comment by rbonghi** [comment]
I think this may be related to this old PRs merged in `develop` and never published: #519 and #523
I'm still working on releasing a new jtop version that fixes all these bugs. otherwise let me know

**Comment by rbonghi** [comment]
I released the new jtop **4.2.9** let me know if fix this bug

```
sudo pip3 install -U jetson-stats
```
