### ISSUE TITLE
Jetpack missing [L4T 32.4.2]

### ISSUE THREAD

**Issue by Robotmad** [rbonghi/jetson_stats#54]
Please update jetson-stats with new jetpack 4.4

**Linux for Tegra**
 - L4T: 32.4.2

**Jetson-Stats**
 - Version: 2.0.3

**Comment by rbonghi** [comment]
Thank you! I will update soon! :-)

**Comment by rbonghi** [comment]
The name of this version is Jetpack 4.4 DP (Developer Preview)

Reference [JetPack 4.4 Developer Preview - L4T R32.4.2 released](https://forums.developer.nvidia.com/t/jetpack-4-4-developer-preview-l4t-r32-4-2-released/120594/17?u=rbonghi)

**Comment by rbonghi** [comment]
New version **2.0.4** released

To update
```bash
sudo -H pip install --no-cache-dir -U jetson_stats
```
To check if the installation is fine and jetson-stats works you can use the health tool running:
```bash
jetson_config
```
Page ***health**
