### ISSUE TITLE
jetson-stats not supported for [L4T 32.7.5]

### ISSUE THREAD

**Issue by Ashington258** [rbonghi/jetson_stats#544]
It did work for a while at first, but after a while, jetpack suddenly couldn't be detected.
And Then：
[WARN] jetson-stats not supported for [L4T 32.7.5]

at the begining：
![9695304f3f5a5338b69d4f9a7931ef6](https://github.com/rbonghi/jetson_stats/assets/58564210/d07f9d7c-8e6f-41de-b857-2b6246ce42cc)

now：
![image](https://github.com/rbonghi/jetson_stats/assets/58564210/1e218613-135b-4ea4-a971-7e87a72dafe0)
![image](https://github.com/rbonghi/jetson_stats/assets/58564210/7af7171a-b560-4341-b04a-fc183287f59c)

I tried `sudo pip3 install -U jetson-stats`,But it doesn't work

**Comment by rbonghi** [comment]
Fixed with the new release. Please update to **4.2.7**

```
sudo pip3 install -U jetson-stats
```
