### ISSUE TITLE
Is "Cur" measured in mA?

### ISSUE THREAD

**Issue by beduffy** [rbonghi/jetson_stats#64]
The Power section of jtop shows [Power/mW], [Cur] and [Avr] columns. What do these mean and is [Cur] measured in mA? 

I'd like to know why because my jetson nano turns off from battery supply and it's either because the iwlwifi module goes up to 120C or because the current reaches 5A.

**Comment by rbonghi** [comment]
Hi @beduffy ,

Welcome to jetson-stats, 
- [curr] means current, at this instant [mW]
- [Avr] means average [mW]

All values are in **mW** (These values are read from tegrastats).

You can estimate the current converting:
Amps [A] = Cur [mW] / V_nano [V] * 10^-3
Where:
V_nano = 5V

I hope my reply is helpful.

**Comment by beduffy** [comment]
Thank you!
