### ISSUE TITLE
jetson_variables missing?

### ISSUE THREAD

**Issue by tikonen** [rbonghi/jetson_stats#69]
**Describe the bug**
Documentation talks about `jetson_variables `script with examples but this script is not available after installing `jetson-stats` package.

**Expected behavior**
Either `jetson_variables` is available after installing `jetson-stats` or is removed from documentation.

**Jtop version**
```
~ $ jtop -v
jtop 2.1.0
```

**Comment by rbonghi** [comment]
Hi @tikonen ,

I did't update my documentation. jetson_variables is an internal script that generate a list of variables for your user. If you run in your shell:

```
export | grep JETSON
```

You will find all jetson variables.

Anyway I'm updating jetson-stats and all documentation. For the beginning of next week I will release a new version

**Comment by tikonen** [comment]
Thank you!
