### ISSUE TITLE
Fan method on jtop returns a Fan object, not a dictionary

### ISSUE THREAD

**Issue by mattarnold98** [rbonghi/jetson_stats#71]
Hi,

The described method return type on jtop.fan is a dictionary (https://github.com/rbonghi/jetson_stats/blob/master/jtop/jtop.py#L340) but it actually returns a Fan object. 

Thanks for writing such a great tool though, great library 👍

**Comment by rbonghi** [comment]
Which version are you using? The new 3.0

Yes, I will fix it. There are some properties that return not dictionaries, are affected:
* jetson_clocks
* nvpmodel
* fan
* swap

I will update soon my documentation

**Comment by mattarnold98** [comment]
Using the new version 3.0, sorry not mentioning it earlier.

Thanks though!
