### ISSUE TITLE
nvdc: nvdcEventThread select failed: Bad file descriptor

### ISSUE THREAD

**Issue by loibucket** [rbonghi/jetson_stats#77]
I get an an error message "nvdc: nvdcEventThread select failed: Bad file descriptor" when starting a new terminal tab in the jupyter lab.  It does not affect operability as the terminal window still works, but there's just this error message when it starts. 

**Describe the bug**

**To Reproduce**
1. Go to '...' jupyter lab on another pc
2. Click on '....' launcher -> new terminal
...
4. See error "nvdc: nvdcEventThread select failed: Bad file descriptor"

**Board**
Jetson nano b01

**Jetpack**
 - Jetpack: [e.g. 4.3] 4.3

**Jetson-Stats**
 - Version: [e.g. 1.8] 3.0.1

**Comment by rbonghi** [comment]
Hi @loibucket ,

Thank you for your message, really clear.
I honestly never tried jtop on *jupyter lab* I will check it and I will keep you posted.

Have you tried jtop outside *jupyter lab*?

**Comment by loibucket** [comment]
Yes, jtop works fine outside jupyter lab.  It also works fine inside jupyter lab's terminal.  The error message just shows up as the first line when a new terminal window is opened inside jupyter lab.  It does not affect the functionality of jtop.

**Comment by rbonghi** [comment]
Hi @loibucket ,

I suggest to write a new post on NVIDIA forum: https://forums.developer.nvidia.com/ 
Watching on google is something on Vulkan
