### ISSUE TITLE
It would be great to add DLA engines as well

### ISSUE THREAD

**Issue by funmonty** [rbonghi/jetson_stats#78]
**Is your feature request related to a problem? Please describe.**
I have been using this tool in my AGX Xavier which has a couple of DLA engines, I could see all the information that is needed for profiling. But Only DLA stats are missing. For that, I would need to do it via a different source.

**Describe the solution you'd like**
It would be great if we can have DLA stats(whatever we could read) in the jtop menu.

Loved using this tool!

**Comment by funmonty** [comment]
Hi,

I would find it manually in the /sys files. For example, the runtime status(active/suspended) can be known in this file /sys/devices/platform/host1x/15880000.nvdla0/power/runtime_status. 

But I'm skeptical about finding details like utilization, frequency, etc. If you can find them, it would be great.

**Comment by rbonghi** [comment]
Now this feature is available with the latest release **4.0** 
```
sudo -H pip install -U jetson-stats
```
