### ISSUE TITLE
Fix little bug in Wiki examples

### ISSUE THREAD

**Issue by charlielito** [rbonghi/jetson_stats#79]
I couldn't find how to make a PR for the Wiki, so here I post it as an issue.

In this [section](https://github.com/rbonghi/jetson_stats/wiki/library) there is this example:
```python
jetson = jtop()
jetson.open()
stat = jetson.stats
jetson.close()
```
It should be `jetson.start()` instead of `jetson.open()`

**Comment by rbonghi** [comment]
Hi @charlielito ,

Thank you! Fixed!

PS: I don't have either idea as well to update via PR the wiki
