### ISSUE TITLE
Description of stats returned by jtop

### ISSUE THREAD

**Issue by muzammil360** [rbonghi/jetson_stats#81]
**Is your feature request related to a problem? Please describe.**
I can get the stats easily, however, I don't know what each stat mean. 

**Describe the solution you'd like**
A wiki referenced on homepage readme explaining each stats with associated unit.

**Describe alternatives you've considered**
I try to guess the stats description based on tegrastats documentation [here](https://docs.nvidia.com/jetson/archives/l4t-archived/l4t-3231/index.html#page/Tegra%20Linux%20Driver%20Package%20Development%20Guide/AppendixTegraStats.html)

**Additional context**
Following is a sample output of my machine. May be explain each one in detail

```
<key>, <value>
time, 2020-09-03 10:28:30.003209
uptime, 22:47:52.710000
jetson_clocks, OFF
nvp model, MAXN
CPU1, 5
CPU2, 3
CPU3, 3
CPU4, 7
CPU5, 5
CPU6, 5
CPU7, 14
CPU8, 1
GPU, 0
MTS FG, 0
MTS BG, 0
RAM, 1745160
EMC, 1745160
SWAP, 0
APE, 150
NVENC, OFF
NVDEC, OFF
NVJPG, OFF
fan, 0.0
Temp AO, 44.5
Temp AUX, 44.5
Temp CPU, 46.0
Temp GPU, 46.0
Temp Tboard, 46.0
Temp Tdiode, 49.25
Temp thermal, 45.4
power cur, 4859
power avg, 4899

```

**Comment by rbonghi** [comment]
Hi @muzammil360 ,

when you read the `stats` property on jtop, you are reading a simplified version of **tegrastats** and other information, you can read this documentation https://rbonghi.github.io/jetson_stats/jtop.html#jtop.jtop.jtop.stats

If you need more details, there are more new proprierties that I suggest, like:
* cpu
* gpu
* ram
* iram
* temperature
* fan
* engine
* ...

You can find all properties here: https://rbonghi.github.io/jetson_stats/jtop.html

**Comment by muzammil360** [comment]
Thanks a lot for quick reply. I was looking for this info. By the way you have done a nice job here writing this library.
