### ISSUE TITLE
Authentication mismatch with jetson-stats server

### ISSUE THREAD

**Issue by CNSaintNeo** [rbonghi/jetson_stats#84]
When I run jtop after being installed，it rise the words that authentication mismatch with jetson-stats server without any hints.
How can we go through this problem， thanks！

**Comment by cylee81** [comment]
Reboot the board is helpful!

**Comment by rbonghi** [comment]
Hi @CNSaintNeo 
I am sorry for my late reply, but if you fixed following the @cylee81 hint this issue should be close. Otherwise, keep free to open again this issue

**Comment by tensorturtle** [comment]
I encountered this issue when trying to use `jtop_logger.py` it in my project. The silly mistake was using Python 3 to run the script instead of Python 2.7.

For example, I should NOT have done `python3 jtop_logger.py`

and instead use: `python jtop_logger.py`.
