### ISSUE TITLE
Board missing: Xavier 32GB

### ISSUE THREAD

**Issue by domcross** [rbonghi/jetson_stats#87]
Please update jetson-stats with this board

**Board**
   - Type: AGX Xavier [16GB]
   - SOC Family: tegra194 - ID:25
   - Module: P2888-0001 - Board: P2822-0000
   - Code Name: galen

**Jetpack**
 - Jetpack: 4.4
 - L4T: 32.4.3

**Jetson-Stats**
 - Version: 3.0.1

My board is Xavier with 32GB RAM but jtop 3.0.1 shows it as "Xavier 16GB" (red markers in attached screenshot). The memory bar shows correct amount though (yellow marker).
![jtop-xavier-32gb](https://user-images.githubusercontent.com/39655102/94681979-8df0b300-0324-11eb-9038-69ac8277b934.png)

**Comment by rbonghi** [comment]
Hi @domcross 

I notice the same bug as well, I need a modification on my jetson variable reader to fix it. After the release to fix #90 I will fix it

**Comment by rbonghi** [comment]
This error should now be fixed with the latest release **4.0** try to install and check again
```
sudo -H pip install -U jetson-stats
```
