### ISSUE TITLE
Log output to file

### ISSUE THREAD

**Issue by ama-jesper** [rbonghi/jetson_stats#89]
We have a headless offline setup where we would like to log the stats to a file.

Is this already possible? If so, could you give a few leads?

**Comment by rbonghi** [comment]
Hi @ama-jesper you can make your personal script to record the jetson status, follow the [examples](https://github.com/rbonghi/jetson_stats/tree/master/examples) and for your case:

https://github.com/rbonghi/jetson_stats/blob/master/examples/jtop_logger.py
