### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by blitzvb** [rbonghi/jetson_stats#9]
Running the pip version, I get that error :

`Traceback (most recent call last):
  File "/usr/local/bin/jtop", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jtop/__main__.py", line 162, in main
    curses.wrapper(gui, args, tegra)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/jtop/__main__.py", line 108, in gui
    stat = tegra.read
  File "/usr/local/lib/python2.7/dist-packages/jtop/jtop.py", line 142, in read
    while not self._jetsonstats:
  File "/usr/local/lib/python2.7/dist-packages/jtop/__main__.py", line 65, in signal_handler
    tegra.close()
NameError: global name 'tegra' is not defined
`

I am running it on a TX1:

declare -x JETSON_BOARD="TX1"
declare -x JETSON_CUDA="9.0.252"
declare -x JETSON_CUDA_ARCH_BIN="5.3"
declare -x JETSON_CUDNN="7.1.5.14-1+cuda9.0"
declare -x JETSON_DESCRIPTION="NVIDIA Jetson NANO/TX1"
declare -x JETSON_JETPACK="3.2"
declare -x JETSON_L4T="28.2.0"
declare -x JETSON_L4T_RELEASE="28"
declare -x JETSON_L4T_REVISION="2.0"
declare -x JETSON_OPENCV="4.1.0"
declare -x JETSON_OPENCV_CUDA="YES"
declare -x JETSON_TENSORRT="4.0.2.0-1+cuda9.0"
declare -x JETSON_TYPE="NANO/TX1"
declare -x JETSON_VISIONWORKS="1.6.0.500n"

nvidia@tegra-ubuntu:~/Desktop$ jetson-release 
/usr/local/bin/jetson-release: line 40: /etc/jetson_easy/jetson_variables: No such file or directory
 - NVIDIA Jetson NANO/TX1
   * Jetpack 3.2 [L4T 28.2.0]
   * CUDA GPU architecture 5.3
 - Libraries:
   * CUDA 9.0.252
   * cuDNN 7.1.5.14-1+cuda9.0
   * TensorRT 4.0.2.0-1+cuda9.0
   * Visionworks 1.6.0.500n
   * OpenCV 4.1.0 compiled CUDA: YES
 - Jetson Performance: inactive

**Comment by rbonghi** [comment]
Can u try to reinstall with:
```
sudo -H pip install --no-cache-dir jetson-stats --upgrade
```
I don't know but sometimes the command "PostInstall" on setup doesn't work well.

Keep me posted if you fix it

**Comment by rbonghi** [comment]
About the error with jetson_release:

I found the path error!
https://github.com/rbonghi/jetson_stats/blob/master/scripts/jetson-release#L40

I will fix soon!

Thank you

**Comment by blitzvb** [comment]
awesome! thx

**Comment by rbonghi** [comment]
About jetson_release 

Meanwhile I fix on my repo you can manually edit in "/usr/local/bin/jetson-release"

and change the line **40** from:
```
source /etc/jetson_easy/jetson_variables
```
to:
```
source /opt/jetson_stats/jetson_variables
```

**Comment by blitzvb** [comment]
your fix, did work perfectly! thx again for that and this must have tool.
